//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class APN_FLIGHT_SECTOR_REVENUE
    {
        public string DEPT_DATE { get; set; }
        public string DEPT_FLT_NO { get; set; }
        public string SECTOR_SEQ { get; set; }
        public string FLT_NO { get; set; }
        public string DEPT_STN { get; set; }
        public string ARIV_STN { get; set; }
        public Nullable<decimal> TOT_RVNU_USD { get; set; }
        public Nullable<int> TOT_RVNU_TWD { get; set; }
        public Nullable<decimal> TOT_COST_USD { get; set; }
        public Nullable<decimal> TOT_SALE_USD { get; set; }
        public Nullable<int> TOT_SALE_TWD { get; set; }
        public Nullable<int> TOT_CSGMT_PAYABLE { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string ACT_DATE { get; set; }
        public string ACT_FLT_NO { get; set; }
        public string ACT_DEPT_STN { get; set; }
        public string ACT_ARIV_STN { get; set; }
        public Nullable<int> TOT_ROYALTY { get; set; }
    
        public virtual APN_FLIGHT_ROUTE_SETTLEMENT APN_FLIGHT_ROUTE_SETTLEMENT { get; set; }
    }
}
