//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class APN_VERSION_QTY_MASTER
    {
        public string VER_TYPE { get; set; }
        public string VER_CLASS { get; set; }
        public string CALC_TYPE { get; set; }
        public string LOAD_NO { get; set; }
        public string REGION_NO { get; set; }
        public string AC_TYPE { get; set; }
        public string DEPT_STN { get; set; }
        public string ARIV_STN { get; set; }
        public string DEPT_FLT_NO { get; set; }
        public string EFF_DATE { get; set; }
        public string EXP_DATE { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string LOCK_FLAG { get; set; }
        public string REMARK { get; set; }
    }
}
