//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class APN_FLIGHT_SCHEDULE_MONTH_B7
    {
        public string DEPT_DATE { get; set; }
        public string DEPT_FLT_NO { get; set; }
        public string ACT_DEPT_STN { get; set; }
        public string ACT_ARIV_STN { get; set; }
        public string ARIV_DATE { get; set; }
        public string ARIV_FLT_NO { get; set; }
        public string ARIV_DEPT_STN { get; set; }
        public string ARIV_ARIV_STN { get; set; }
    }
}
