//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class APN_FLIGHT_ROUTE_SETTLEMENT
    {
        public APN_FLIGHT_ROUTE_SETTLEMENT()
        {
            this.APN_FLIGHT_SECTOR_REVENUE = new HashSet<APN_FLIGHT_SECTOR_REVENUE>();
            this.CRW_CUST_PURCHASE_MASTER = new HashSet<CRW_CUST_PURCHASE_MASTER>();
            this.CRW_FLIGHT_CAR_CONTROL = new HashSet<CRW_FLIGHT_CAR_CONTROL>();
        }
    
        public string DEPT_DATE { get; set; }
        public string DEPT_FLT_NO { get; set; }
        public string AC_TYPE { get; set; }
        public string AC_NO { get; set; }
        public string G_NO { get; set; }
        public string DEPARTMENT_NO { get; set; }
        public string USER_ID { get; set; }
        public string LOCK_MARK { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string DIFF_ID { get; set; }
        public string DIFF_MENO { get; set; }
        public string BCR_G_NO { get; set; }
        public string BCR_STOCK_MONTH { get; set; }
        public string BCR_C_NO { get; set; }
        public string BCR_G_NO_B { get; set; }
        public string BCR_C_NO_B { get; set; }
        public string BCR_G_NO_C { get; set; }
        public string BCR_C_NO_C { get; set; }
        public string H_NO { get; set; }
        public string G_NO_1 { get; set; }
        public string G_NO_2 { get; set; }
        public string G_NO_9 { get; set; }
    
        public virtual APN_FLIGHT_BAR_CART_CONTROL APN_FLIGHT_BAR_CART_CONTROL { get; set; }
        public virtual ICollection<APN_FLIGHT_SECTOR_REVENUE> APN_FLIGHT_SECTOR_REVENUE { get; set; }
        public virtual ICollection<CRW_CUST_PURCHASE_MASTER> CRW_CUST_PURCHASE_MASTER { get; set; }
        public virtual ICollection<CRW_FLIGHT_CAR_CONTROL> CRW_FLIGHT_CAR_CONTROL { get; set; }
    }
}
