//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARGCCPT
    {
        public string CPT_CNTL { get; set; }
        public string CPT_TYPE { get; set; }
        public string CPT_EFF_DATE { get; set; }
        public string CPT_EXP_DATE { get; set; }
        public Nullable<int> CPT_UNIT_VALUE { get; set; }
        public string CPT_IN_USER { get; set; }
        public string CPT_IN_DATE { get; set; }
    }
}
