//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUT_PROGRAM
    {
        public string PROG_NAME { get; set; }
        public string PROG_DESC { get; set; }
        public string CLASS { get; set; }
        public string PROG_PATH { get; set; }
        public string REMARK { get; set; }
        public string STATUS { get; set; }
        public string DEPT { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string FUN01 { get; set; }
        public string FUN02 { get; set; }
        public string FUN03 { get; set; }
        public string FUN04 { get; set; }
        public string FUN05 { get; set; }
        public string FUN06 { get; set; }
        public string FUN07 { get; set; }
        public string FUN08 { get; set; }
        public string FUN09 { get; set; }
        public string FUN10 { get; set; }
        public string FUN11 { get; set; }
        public string FUN12 { get; set; }
        public string FUN13 { get; set; }
        public string FUN14 { get; set; }
        public string FUN15 { get; set; }
        public string FUN16 { get; set; }
        public string FUN17 { get; set; }
        public string FUN18 { get; set; }
        public string FUN19 { get; set; }
        public string FUN20 { get; set; }
    }
}
