//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUT_WORK_FLOW_LOG_ST15000002
    {
        public string SEQ_NO { get; set; }
        public string CARD_ID { get; set; }
        public string DEPARTMENT_NO_S { get; set; }
        public string EMPLOYEE_NO_S { get; set; }
        public string DATE_S { get; set; }
        public string TIME_S { get; set; }
        public string DEPARTMENT_NO_A { get; set; }
        public string POS_SEQ_START { get; set; }
        public string POS_SEQ_END { get; set; }
        public string AUTHORITY { get; set; }
        public string PATH_ID { get; set; }
        public string EMPLOYEE_NO_A { get; set; }
        public string REMARK { get; set; }
        public string DATE_A { get; set; }
        public string TIME_A { get; set; }
        public string STATUS { get; set; }
        public string TRANS_NO { get; set; }
        public string MANAGER { get; set; }
        public string STATUS_A { get; set; }
        public string DEPARTMENT_SUB_NO_A { get; set; }
        public string DEPARTMENT_SUB_NO_S { get; set; }
        public string SYSTEM_FLAG { get; set; }
    }
}
