//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class B2B_SUPPLY_LOG
    {
        public string SEQ_NO { get; set; }
        public string VENDOR_NO { get; set; }
        public string CODE { get; set; }
        public Nullable<int> MINNUM_QTY { get; set; }
        public Nullable<decimal> SUPPLY_PRICE { get; set; }
        public Nullable<decimal> ADVISED_PRICE { get; set; }
        public Nullable<decimal> DUTY_FREE_PRICE { get; set; }
        public Nullable<decimal> AVERAGE_PRICE { get; set; }
        public Nullable<int> COEFFICIENT { get; set; }
        public string PAYMENT_TERM_NO { get; set; }
        public string DELIVERY_TERM { get; set; }
        public string STORE_UNIT { get; set; }
        public string PACKAGE_UNIT { get; set; }
        public string PRICE_CHANGE_DATE { get; set; }
        public string CURRENCY_TYPE { get; set; }
        public string QUOTATION_VALID_DATE { get; set; }
        public string EFF_DATE { get; set; }
        public string EXP_DATE { get; set; }
        public string AGENT { get; set; }
        public string AGENT_ADDRESS { get; set; }
        public string CLERK { get; set; }
        public string CLERK_ADDRESS { get; set; }
        public string CLERK_TEL { get; set; }
        public string MAIL_ADDRESS { get; set; }
        public string ORIGINAL_CODE { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
    }
}
