//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class B2B_PURCHASE_NOTICE
    {
        public string PURCHASE_NO { get; set; }
        public string VERSION { get; set; }
        public string PURCHASE_TEXT { get; set; }
        public string PURCHASE_SPEC { get; set; }
        public string START_DATE { get; set; }
        public string END_DATE { get; set; }
        public string PAY_TYPE { get; set; }
        public string DELIVERY_TYPE { get; set; }
        public string DELIVERY_ADDRESS { get; set; }
        public string CONTACT_NAME { get; set; }
        public string CONTACT_TEL { get; set; }
        public string CONTACT_EMAIL { get; set; }
        public string SUPPLY_CONDITION { get; set; }
        public string REMARK_TEXT { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public byte[] IMAGE { get; set; }
        public byte[] DOCUMENT { get; set; }
        public string DOCUMENT_TYPE { get; set; }
        public string IMAGE_TYPE { get; set; }
    }
}
