//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class B2C_PACKAGE_DETAILS_PRICE_LOG
    {
        public string B2C_CODE { get; set; }
        public string SMAS_CODE { get; set; }
        public string EFF_DATE { get; set; }
        public short LOG_SEQ { get; set; }
        public Nullable<int> PRICE { get; set; }
        public Nullable<decimal> PRICE_RATIO { get; set; }
        public string STATUS { get; set; }
        public string CHANGE_ID { get; set; }
        public string CHANGE_DATE { get; set; }
        public Nullable<int> PRICE_MBR { get; set; }
    }
}
