//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class B2C_ECOUPON_CONDITION_LOG
    {
        public string COND_ID { get; set; }
        public string COND_TYPE { get; set; }
        public string COND_NAME { get; set; }
        public Nullable<int> COUPON_AMT { get; set; }
        public string LAUNCH_DATE { get; set; }
        public string STOP_DATE { get; set; }
        public string LAUNCH_FLAG { get; set; }
        public string ECOUPON_EFF_DATE { get; set; }
        public string ECOUPON_EXP_DATE { get; set; }
        public string CUST_TYPE { get; set; }
        public string FFP_CARD_TYPE { get; set; }
        public string COND_XPEND_FROM_DATE { get; set; }
        public string COND_XPEND_TO_DATE { get; set; }
        public Nullable<int> COND_XPEND_AMT { get; set; }
        public Nullable<short> COND_XPEND_COUNT { get; set; }
        public string ORDER_FROM { get; set; }
        public string PAY_TYPE { get; set; }
        public string CUST_SEX { get; set; }
        public Nullable<short> AGE_FROM { get; set; }
        public Nullable<short> AGE_TO { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
    }
}
