//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class B2C_ORDER_RETURN_LOG
    {
        public string ORDER_NO { get; set; }
        public string B2C_CODE { get; set; }
        public string CODE { get; set; }
        public Nullable<int> UNIT_PRICE { get; set; }
        public Nullable<int> UNIT_MILEAGE { get; set; }
        public Nullable<int> ORDER_SUIT_QTY { get; set; }
        public Nullable<int> UNIT_QTY { get; set; }
        public Nullable<short> ORDER_QTY { get; set; }
        public string DISC_FLAG { get; set; }
        public Nullable<int> DISC { get; set; }
        public Nullable<int> SUB_TOTAL { get; set; }
        public Nullable<int> SUB_MILEAGE { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public short ORDER_SEQ { get; set; }
    }
}
