//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class B2C_STAR_USAGE
    {
        public string ORDER_NO { get; set; }
        public string CUST_ID { get; set; }
        public string CUST_NBR { get; set; }
        public string CUST_NAME { get; set; }
        public Nullable<int> GET_STAR_CNT { get; set; }
        public Nullable<int> USE_STAR_CNT { get; set; }
        public Nullable<int> RTN_STAR_CNT { get; set; }
        public Nullable<int> AVL_STAR_CNT { get; set; }
        public string GET_DATE { get; set; }
        public string USE_DATE { get; set; }
        public string RTN_DATE { get; set; }
        public string STAR_EFF_DATE { get; set; }
        public string ORIGIN_NO { get; set; }
        public string ORDER_TYPE { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string STAR_EXP_DATE { get; set; }
    }
}
