//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class B2C_ORDER_CUSTOMER_LOG
    {
        public string LOG_ACTION { get; set; }
        public string ORDER_NO { get; set; }
        public string ORDER_DATE { get; set; }
        public string CUST_NAME { get; set; }
        public string CUST_SEX { get; set; }
        public string CUST_BIRTH { get; set; }
        public string CUST_TEL_O { get; set; }
        public string CUST_TEL_H { get; set; }
        public string CUST_TEL_M { get; set; }
        public string CUST_FAX { get; set; }
        public string CUST_EMAIL { get; set; }
        public string CUST_ZIP_CODE { get; set; }
        public string CUST_ADDRESS { get; set; }
        public string RCVR_NAME { get; set; }
        public string RCVR_SEX { get; set; }
        public string RCVR_TEL_O { get; set; }
        public string RCVR_TEL_H { get; set; }
        public string RCVR_TEL_M { get; set; }
        public string RCVR_ZIP_CODE { get; set; }
        public string RCVR_ADDRESS { get; set; }
        public string RTN_FLAG { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
    }
}
