//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class B2C_CATALOG_PRODUCTS
    {
        public string B2C_CODE { get; set; }
        public string B2C_CODE_NAME { get; set; }
        public string PROD_DESC { get; set; }
        public string PROD_SPEC { get; set; }
        public string STORE_UNIT { get; set; }
        public string PACKAGE_UNIT { get; set; }
        public string COEFFICIENT { get; set; }
        public string CONSIGNED { get; set; }
        public Nullable<int> CSGMT_COST { get; set; }
        public Nullable<int> CSGMT_QTY { get; set; }
        public Nullable<int> MAX_ORDER_QTY { get; set; }
        public Nullable<int> MIN_ORDER_QTY { get; set; }
        public string PROD_STYLE_NAME { get; set; }
        public Nullable<int> PROPOSE_PRICE { get; set; }
        public Nullable<int> ACT_PRICE { get; set; }
        public string START_DATE { get; set; }
        public string END_DATE { get; set; }
        public string APPROVED_STATUS { get; set; }
        public string APPROVED_BY { get; set; }
        public string APPROVED_DATE { get; set; }
        public string LIGHT_STATUS { get; set; }
        public string PROD_CATG_NAME { get; set; }
        public string PROD_CATG_ORDER { get; set; }
        public string RRE_ORDER { get; set; }
        public Nullable<int> RRE_ORDER_QTY { get; set; }
        public string RELATED_PROD { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
    }
}
