//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class B2C_CODE_MAPPING_MASTER
    {
        public string B2C_CODE { get; set; }
        public string B2C_CODE_NAME { get; set; }
        public string PROD_INFO { get; set; }
        public string PROD_SPEC { get; set; }
        public string STORE_UNIT { get; set; }
        public string PACKAGE_UNIT { get; set; }
        public Nullable<int> COEFFICIENT { get; set; }
        public string CONSIGNED { get; set; }
        public Nullable<int> CSGMT_COST { get; set; }
        public Nullable<int> CSGMT_QTY { get; set; }
        public Nullable<int> MAX_ORDER_QTY { get; set; }
        public Nullable<int> MIN_ORDER_QTY { get; set; }
        public string PROD_STYLE_NAME { get; set; }
        public Nullable<int> PROPOSE_PRICE { get; set; }
        public Nullable<int> ACT_PRICE { get; set; }
        public Nullable<decimal> TAX_RATE { get; set; }
        public string IMAGE_PATH_HOT { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string TRN_ID { get; set; }
        public string TRN_DATE { get; set; }
        public string TRN_TIME { get; set; }
        public string PRE_MARK { get; set; }
        public string PRE_START { get; set; }
        public string PRE_END { get; set; }
        public Nullable<int> PRE_QTY { get; set; }
        public string NON_ENT_FLAG { get; set; }
    }
}
