//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class B2C_ORDER_PAYMENT
    {
        public string ORDER_NO { get; set; }
        public string PAY_SEQ { get; set; }
        public string PAY_TYPE { get; set; }
        public string ACCOUNT_NO { get; set; }
        public string EXP_DATE { get; set; }
        public string COUPON_NO_FROM { get; set; }
        public string COUPON_NO_TO { get; set; }
        public Nullable<short> COUPON_QTY { get; set; }
        public Nullable<int> PAY_AMT { get; set; }
        public string ACCOUNT_DATE { get; set; }
        public string REMARK { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string AUTH_CODE { get; set; }
        public string PSEUDO_ACCOUNT_NO { get; set; }
        public string CCA_RTN_VALUE { get; set; }
        public string CARD_CHK_CODE { get; set; }
        public string GET_AUTH_KEY { get; set; }
        public string BANK_PROC_DATE { get; set; }
        public string BANK_RSP_CODE { get; set; }
        public string BANK_RSP_DESC { get; set; }
        public string BANK_BATCH_SEQ { get; set; }
    }
}
