//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class B2C_PROMOTION_MASTER_20140103
    {
        public string PMT_ID { get; set; }
        public string PMT_NAME { get; set; }
        public string PMT_DESC { get; set; }
        public string CUST_TYPE { get; set; }
        public string FFP_CARD_TYPE { get; set; }
        public string BRENCH { get; set; }
        public string PMT_TYPE { get; set; }
        public Nullable<int> PMT_AMT { get; set; }
        public string PMT_AMT_TYPE { get; set; }
        public string PMT_PRIORITY { get; set; }
        public string PMT_RELATION { get; set; }
        public string MAIL_ORDER_FLAG { get; set; }
        public string PAY_TYPE { get; set; }
        public string EFF_DATE { get; set; }
        public string EXP_DATE { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string RETURN_MSG { get; set; }
    }
}
