//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class B2C_LISTING_FEE_DETAILS
    {
        public string LT_NO { get; set; }
        public string PERIOD { get; set; }
        public string VENDOR_NO { get; set; }
        public string INVOICE_TYPE { get; set; }
        public string CHARGE_TYPE { get; set; }
        public string CODE { get; set; }
        public Nullable<short> PAGE { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
        public Nullable<short> MONTH { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string CAL_CURRENCY { get; set; }
    }
}
