//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class B2C_WEB_CONTENT
    {
        public string CODE { get; set; }
        public string CODE_TYPE { get; set; }
        public string DOC_VER { get; set; }
        public string TRANS_NO { get; set; }
        public string STATUS { get; set; }
        public string DOC_BODY { get; set; }
        public string DOC_PIC1_PATH { get; set; }
        public string DOC_PIC2_PATH { get; set; }
        public string DOC_PIC3_PATH { get; set; }
        public string DOC_PIC4_PATH { get; set; }
        public string DOC_PIC5_PATH { get; set; }
        public string DOC_SPEC_PIC { get; set; }
        public string DOC_EFF_DATE { get; set; }
        public string DOC_EXP_DATE { get; set; }
        public string DOC_DISABLE { get; set; }
        public string SUBMIT_DATETIME { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string DOC_MEMO { get; set; }
        public string MODIFY_MGR_ID { get; set; }
        public string MODIFY_MGR_DATE { get; set; }
        public string MODIFY_MGR_TIME { get; set; }
    }
}
