//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAS_DATA_INTERFACE
    {
        public string INTERFACE_ID { get; set; }
        public string SERVER_PATH { get; set; }
        public string USER_ID { get; set; }
        public string PASSWORD { get; set; }
        public string DESCRIPTION { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string PROG_ID { get; set; }
        public string SCHEDULE { get; set; }
        public string IP { get; set; }
        public Nullable<decimal> DATA_DUE_DATE_CNT { get; set; }
        public string FILE_EXCLUDE { get; set; }
    }
}
