//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAS_FLIGHT_SCHEDULE_B7
    {
        public string DEPT_DATE { get; set; }
        public string DEPT_TIME { get; set; }
        public string DEPT_FLT_NO { get; set; }
        public string DEPT_STN { get; set; }
        public string ARIV_STN { get; set; }
        public string AC_TYPE { get; set; }
        public string AC_NO { get; set; }
        public string SERVICE_TYPE { get; set; }
        public string FLT_REGION { get; set; }
        public string AIRCRAFT_PAX_CARGO { get; set; }
        public string FLIGHT_ROUTE_NO { get; set; }
        public Nullable<System.DateTime> ROUTE_START_DATETIME { get; set; }
        public string ORIGINAL_DEPT_DATE { get; set; }
        public string ORIGINAL_DEPT_TIME { get; set; }
        public Nullable<short> F_PAX_CFG { get; set; }
        public Nullable<short> C_PAX_CFG { get; set; }
        public Nullable<short> ED_PAX_CFG { get; set; }
        public Nullable<short> Y_PAX_CFG { get; set; }
        public Nullable<short> F_PAX_BKD { get; set; }
        public Nullable<short> C_PAX_BKD { get; set; }
        public Nullable<short> ED_PAX_BKD { get; set; }
        public Nullable<short> Y_PAX_BKD { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
    }
}
