//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAS_REFERENCE_DATA_DETAILS
    {
        public string CONFIG_TYPE { get; set; }
        public string CONFIG_KEY { get; set; }
        public string CONFIG_VALUE { get; set; }
        public string CONFIG_CHINESE_DESC { get; set; }
        public string CONFIG_ENGLISH_DESC { get; set; }
        public Nullable<int> CONFIG_PRINT_SEQ { get; set; }
        public Nullable<int> ORDER_NUM { get; set; }
        public string ENABLED { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public Nullable<int> SEQ { get; set; }
    }
}
