//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAS_MATERIAL_REMARK_LOG
    {
        public string CODE { get; set; }
        public int LOG_SEQ { get; set; }
        public string DEPARTMENT_NO { get; set; }
        public string DEPARTMENT_SUB_NO { get; set; }
        public string REMARK_TXT { get; set; }
        public string REQUEST_STATUS { get; set; }
        public string REQUEST_DATE { get; set; }
        public string APPROVE_DATETIME { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
    }
}
