//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAS_MATERIAL_CLASS
    {
        public string CLASS_LEVEL { get; set; }
        public string CLASS { get; set; }
        public string SUBCLASS { get; set; }
        public string CLASS_NAME { get; set; }
        public string SUBCLASS_NAME { get; set; }
        public string BUDGET_CODE { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string CHK_PUS_USER { get; set; }
        public string CHK_RDS_USER { get; set; }
        public string SCR_FLAG { get; set; }
    }
}
