//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAS_STORE
    {
        public string STORE_NO { get; set; }
        public string DESCRIPTION { get; set; }
        public string TRANS_MARK { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string DEPARTMENT_NO { get; set; }
        public string STORE_TYPE { get; set; }
        public string BONDED { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string SIGN_FLAG { get; set; }
        public string ADDRESS3 { get; set; }
        public string ROUTE_TYPE { get; set; }
    }
}
