//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAS_MATERIAL
    {
        public string CODE { get; set; }
        public string ACCOUNT_CODE { get; set; }
        public string STORE_UNIT { get; set; }
        public string PACKAGE_UNIT { get; set; }
        public Nullable<int> COEFFICIENT { get; set; }
        public string ENGLISH_SHORTNAME { get; set; }
        public string ENGLISH_FULLNAME { get; set; }
        public string CHINESE_SHORTNAME { get; set; }
        public string CHINESE_FULLNAME { get; set; }
        public string BONDED { get; set; }
        public string CONSIGNED { get; set; }
        public string MATERIAL_TYPE { get; set; }
        public string CLASS { get; set; }
        public string SUBCLASS { get; set; }
        public string MONTH_END_MODE { get; set; }
        public string SUPPLY_APN_MODE { get; set; }
        public string SUPPLY_MODE { get; set; }
        public string PO_FLAG { get; set; }
        public Nullable<decimal> DIMENSION_L { get; set; }
        public Nullable<decimal> DIMENSION_W { get; set; }
        public Nullable<decimal> DIMENSION_H { get; set; }
        public Nullable<decimal> GROSS_WEIGHT { get; set; }
        public Nullable<short> LEAD_TIME { get; set; }
        public Nullable<short> SAFE_PERIOD { get; set; }
        public string NOTE { get; set; }
        public Nullable<decimal> CURR_UNIT_PRICE { get; set; }
        public Nullable<decimal> CURR_QTY { get; set; }
        public Nullable<int> CURR_AMT { get; set; }
        public string PACK_DETAIL { get; set; }
        public Nullable<int> SCR_SAFE_QTY { get; set; }
        public Nullable<decimal> UNIFORM_COST { get; set; }
        public string UNIFORM_REMARK { get; set; }
        public string BOND_DESCRIPTION { get; set; }
        public Nullable<short> SCR_SET { get; set; }
        public Nullable<short> EFFECT_DAYS { get; set; }
        public string RELAY_CODE { get; set; }
        public string RELAY_DATE { get; set; }
        public string PRODUCT_CODE { get; set; }
        public Nullable<short> EXP_DATE { get; set; }
        public Nullable<short> DEPRECIATION_YEAR { get; set; }
        public string STORE_NO { get; set; }
        public string VENDOR_NO { get; set; }
        public string POSBK_CODE { get; set; }
        public string RFID_CODE { get; set; }
        public string RFIDBK_CODE { get; set; }
        public string REMARK { get; set; }
        public Nullable<int> MAXNUM { get; set; }
        public string UNIFORM_SIZE { get; set; }
        public string REPLACE_YEAR { get; set; }
        public string REQUEST_STATUS { get; set; }
        public string REQUEST_DATE { get; set; }
        public string ENCODE_CLASS { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string LAST_REQUEST_DATE { get; set; }
        public string USE_TYPE_C { get; set; }
        public string USE_TYPE_P { get; set; }
        public string USE_TYPE_G { get; set; }
        public Nullable<decimal> LAST_B_UNIT_PRICE { get; set; }
        public string UNI_TYPE_CODE { get; set; }
        public Nullable<short> SCR_SET_KHH { get; set; }
        public Nullable<short> SCR_SET_TXG { get; set; }
        public Nullable<decimal> PURCHASE_TIME { get; set; }
        public string UNI_CODE_FLAG { get; set; }
        public string KITTY_FLAG { get; set; }
        public string KITTY_CLASS { get; set; }
        public string REQUEST_STATUS_PRE { get; set; }
        public string REQUEST_STATUS_WEB { get; set; }
        public string REQUEST_DATE_PRE { get; set; }
        public string REQUEST_DATE_WEB { get; set; }
        public Nullable<int> EGSC_COEFFICIENT { get; set; }
        public string EGSC_PACKAGE_UNIT { get; set; }
        public string CHINESE_COMMON_NAME { get; set; }
        public string SCR_TYPE { get; set; }
    }
}
