//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAS_SHOPPING_COUPON
    {
        public int COUPON_ID { get; set; }
        public string COUPON_NAME { get; set; }
        public string COUPON_DESC { get; set; }
        public Nullable<short> COUPON_AMT { get; set; }
        public string COUPON_CURRENCY { get; set; }
        public string EFF_DATE { get; set; }
        public string EXP_DATE { get; set; }
        public string COUPON_NO_FROM { get; set; }
        public string COUPON_NO_TO { get; set; }
        public Nullable<int> COUPON_CNT { get; set; }
        public Nullable<decimal> SALE_DISC { get; set; }
        public string SALE_COMPANY { get; set; }
        public string SALE_COMPANY_ID { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string AUT_ID { get; set; }
        public string AUT_DATE { get; set; }
        public string AUT_TIME { get; set; }
        public string REMARK { get; set; }
        public string FIN_TYPE { get; set; }
    }
}
