//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUD_ACTUAL_PAX_COUNT
    {
        public string YEAR { get; set; }
        public string VERSION { get; set; }
        public string CLASS { get; set; }
        public Nullable<int> F_SH_PAX_CNT { get; set; }
        public Nullable<int> F_NH_PAX_CNT { get; set; }
        public Nullable<int> F_LH_PAX_CNT { get; set; }
        public Nullable<int> C_SH_PAX_CNT { get; set; }
        public Nullable<int> C_NH_PAX_CNT { get; set; }
        public Nullable<int> C_LH_PAX_CNT { get; set; }
        public Nullable<int> ED_SH_PAX_CNT { get; set; }
        public Nullable<int> ED_NH_PAX_CNT { get; set; }
        public Nullable<int> ED_LH_PAX_CNT { get; set; }
        public Nullable<int> Y_SH_PAX_CNT { get; set; }
        public Nullable<int> Y_NH_PAX_CNT { get; set; }
        public Nullable<int> Y_LH_PAX_CNT { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string BUDGET_MONTH { get; set; }
        public Nullable<int> F_DL_PAX_CNT { get; set; }
        public Nullable<int> C_DL_PAX_CNT { get; set; }
        public Nullable<int> ED_DL_PAX_CNT { get; set; }
        public Nullable<int> Y_DL_PAX_CNT { get; set; }
    }
}
