//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUD_BUDGET_CONSUMPTION_SUMMARY
    {
        public string YEAR { get; set; }
        public string VERSION { get; set; }
        public string CLASS { get; set; }
        public string DURATION { get; set; }
        public string DURATION_SINGLE { get; set; }
        public string BUDGET_NO { get; set; }
        public Nullable<long> F_SH_PAX_CNT { get; set; }
        public Nullable<long> F_NH_PAX_CNT { get; set; }
        public Nullable<long> F_LH_PAX_CNT { get; set; }
        public Nullable<long> C_SH_PAX_CNT { get; set; }
        public Nullable<long> C_NH_PAX_CNT { get; set; }
        public Nullable<long> C_LH_PAX_CNT { get; set; }
        public Nullable<long> ED_SH_PAX_CNT { get; set; }
        public Nullable<long> ED_NH_PAX_CNT { get; set; }
        public Nullable<long> ED_LH_PAX_CNT { get; set; }
        public Nullable<long> Y_SH_PAX_CNT { get; set; }
        public Nullable<long> Y_NH_PAX_CNT { get; set; }
        public Nullable<long> Y_LH_PAX_CNT { get; set; }
        public Nullable<decimal> F_SH_UNIT_COST { get; set; }
        public Nullable<decimal> F_NH_UNIT_COST { get; set; }
        public Nullable<decimal> F_LH_UNIT_COST { get; set; }
        public Nullable<decimal> C_SH_UNIT_COST { get; set; }
        public Nullable<decimal> C_NH_UNIT_COST { get; set; }
        public Nullable<decimal> C_LH_UNIT_COST { get; set; }
        public Nullable<decimal> ED_SH_UNIT_COST { get; set; }
        public Nullable<decimal> ED_NH_UNIT_COST { get; set; }
        public Nullable<decimal> ED_LH_UNIT_COST { get; set; }
        public Nullable<decimal> Y_SH_UNIT_COST { get; set; }
        public Nullable<decimal> Y_NH_UNIT_COST { get; set; }
        public Nullable<decimal> Y_LH_UNIT_COST { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string BUDGET_CODE { get; set; }
        public string IS_EXPORT { get; set; }
        public Nullable<long> F_DL_PAX_CNT { get; set; }
        public Nullable<long> C_DL_PAX_CNT { get; set; }
        public Nullable<long> ED_DL_PAX_CNT { get; set; }
        public Nullable<long> Y_DL_PAX_CNT { get; set; }
        public Nullable<decimal> F_DL_UNIT_COST { get; set; }
        public Nullable<decimal> C_DL_UNIT_COST { get; set; }
        public Nullable<decimal> ED_DL_UNIT_COST { get; set; }
        public Nullable<decimal> Y_DL_UNIT_COST { get; set; }
    }
}
