//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUD_BUDGET_CONSUMPTION_MASTER
    {
        public string YEAR { get; set; }
        public string VERSION { get; set; }
        public string CLASS { get; set; }
        public string DURATION { get; set; }
        public string DURATION_SINGLE { get; set; }
        public string BUDGET_NO { get; set; }
        public Nullable<decimal> FREIGHT_RATE { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public Nullable<short> SHORT_MILEAGE { get; set; }
        public Nullable<short> LONG_MILEAGE { get; set; }
        public string BUDGET_CODE { get; set; }
        public string IS_TRAN { get; set; }
    }
}
