//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUD_BUDGET_MATERIAL_CLASS
    {
        public string YEAR { get; set; }
        public string VERSION { get; set; }
        public string CODE { get; set; }
        public string F_SH_PAX_CNT { get; set; }
        public string F_NH_PAX_CNT { get; set; }
        public string F_LH_PAX_CNT { get; set; }
        public string C_SH_PAX_CNT { get; set; }
        public string C_NH_PAX_CNT { get; set; }
        public string C_LH_PAX_CNT { get; set; }
        public string ED_SH_PAX_CNT { get; set; }
        public string ED_NH_PAX_CNT { get; set; }
        public string ED_LH_PAX_CNT { get; set; }
        public string Y_SH_PAX_CNT { get; set; }
        public string Y_NH_PAX_CNT { get; set; }
        public string Y_LH_PAX_CNT { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string STATUS { get; set; }
        public string PL_SH_PAX_CNT { get; set; }
        public string PL_NH_PAX_CNT { get; set; }
        public string PL_LH_PAX_CNT { get; set; }
        public string EL_SH_PAX_CNT { get; set; }
        public string EL_NH_PAX_CNT { get; set; }
        public string EL_LH_PAX_CNT { get; set; }
        public string OTHER { get; set; }
        public string F_DL_PAX_CNT { get; set; }
        public string C_DL_PAX_CNT { get; set; }
        public string ED_DL_PAX_CNT { get; set; }
        public string Y_DL_PAX_CNT { get; set; }
        public string PL_DL_PAX_CNT { get; set; }
        public string EL_DL_PAX_CNT { get; set; }
    }
}
