//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUD_BUDGET_SCR_DETAILS
    {
        public string YEAR { get; set; }
        public string VERSION { get; set; }
        public string CLASS { get; set; }
        public string TYPE { get; set; }
        public Nullable<decimal> JAN_RATIO { get; set; }
        public Nullable<decimal> FEB_RATIO { get; set; }
        public Nullable<decimal> MAR_RATIO { get; set; }
        public Nullable<decimal> APR_RATIO { get; set; }
        public Nullable<decimal> MAY_RATIO { get; set; }
        public Nullable<decimal> JUN_RATIO { get; set; }
        public Nullable<decimal> JUL_RATIO { get; set; }
        public Nullable<decimal> AUG_RATIO { get; set; }
        public Nullable<decimal> SEP_RATIO { get; set; }
        public Nullable<decimal> OCT_RATIO { get; set; }
        public Nullable<decimal> NOV_RATIO { get; set; }
        public Nullable<decimal> DEC_RATIO { get; set; }
        public Nullable<int> JAN_AMT { get; set; }
        public Nullable<int> FEB_AMT { get; set; }
        public Nullable<int> MAR_AMT { get; set; }
        public Nullable<int> APR_AMT { get; set; }
        public Nullable<int> MAY_AMT { get; set; }
        public Nullable<int> JUN_AMT { get; set; }
        public Nullable<int> JUL_AMT { get; set; }
        public Nullable<int> AUG_AMT { get; set; }
        public Nullable<int> SEP_AMT { get; set; }
        public Nullable<int> OCT_AMT { get; set; }
        public Nullable<int> NOV_AMT { get; set; }
        public Nullable<int> DEC_AMT { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
    }
}
