//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_ROYALTY
    {
        public string PURCHASE_NO { get; set; }
        public short PURCHASE_SEQ { get; set; }
        public string CODE { get; set; }
        public string CURRENCY_TYPE { get; set; }
        public Nullable<decimal> ORDER_UNIT_PRICE { get; set; }
        public string ROYALTY_CODE { get; set; }
        public Nullable<decimal> ROY_EX_RATE { get; set; }
        public decimal PRICE { get; set; }
        public decimal ROY_UNIT_PRICE { get; set; }
        public Nullable<int> ORDER_QTY { get; set; }
        public string STATUS { get; set; }
        public string PAY_FLAG { get; set; }
        public string PAY_DATE { get; set; }
        public string TRANS_FLAG { get; set; }
        public string TRANS_DATE { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public Nullable<int> ERASE_QTY { get; set; }
        public Nullable<decimal> ERASE_AMOUNT { get; set; }
        public string TRANS_NO { get; set; }
        public Nullable<decimal> ORG_TOTAL { get; set; }
    }
}
