//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRW_FLIGHT_CAR_CONTROL
    {
        public string DEPT_DATE { get; set; }
        public string DEPT_FLT_NO { get; set; }
        public string DOC_NO { get; set; }
        public string DOC_NO_SEQ { get; set; }
        public string STND_LOAD_NO { get; set; }
        public string STND_LOAD_AREA { get; set; }
        public string DOWN_LOAD_MARK { get; set; }
        public string UP_LOAD_MARK { get; set; }
        public string RTN_FLT_MARK { get; set; }
        public string POS_MARK { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string PREORD_DOWN_LOAD_MARK { get; set; }
        public string POS_DOWN_DATE { get; set; }
        public string POS_DOWN_TIME { get; set; }
        public string STND_SITE { get; set; }
        public string ADJ_MARK { get; set; }
        public string POS_NO { get; set; }
        public string PAIR_MARK { get; set; }
    
        public virtual APN_FLIGHT_ROUTE_SETTLEMENT APN_FLIGHT_ROUTE_SETTLEMENT { get; set; }
    }
}
