//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRW_SCR_COST_PRICE_LOG
    {
        public string CODE { get; set; }
        public short SEQ { get; set; }
        public string EFF_DATE { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<decimal> COST { get; set; }
        public string CSGMT_VENDOR { get; set; }
        public string CSGMT_CURRENCY { get; set; }
        public Nullable<decimal> CSGMT_COST { get; set; }
        public string USER_ID { get; set; }
        public string CHANGE_DATE { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> SALE_TWD { get; set; }
        public Nullable<decimal> REF_PRICE { get; set; }
        public Nullable<decimal> REF_COST { get; set; }
        public Nullable<decimal> SUPPLY_PRICE { get; set; }
        public string SUPPLY_CURRENCY { get; set; }
    }
}
