//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRW_DAILY_CASH_SUMMARY
    {
        public string RVNU_DATE { get; set; }
        public Nullable<int> PAY_TWD { get; set; }
        public Nullable<decimal> PAY_USD { get; set; }
        public Nullable<int> RCVD_TWD { get; set; }
        public Nullable<int> SALE_TWD { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string JOB_NAME { get; set; }
        public string DEPT_MONTH { get; set; }
        public string RVNU_MONTH { get; set; }
    }
}
