//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRW_DEBIT_NOTE_MASTER
    {
        public string DN_NO { get; set; }
        public string CA_NO { get; set; }
        public string PERIOD { get; set; }
        public Nullable<int> TOT_AMT { get; set; }
        public Nullable<int> PAY_1 { get; set; }
        public Nullable<int> PAY_2 { get; set; }
        public Nullable<int> CASH_PAY { get; set; }
        public Nullable<int> WAIVE_PAY { get; set; }
        public Nullable<int> ACC_PAY { get; set; }
        public Nullable<int> UNREC_AMT { get; set; }
        public Nullable<int> WAIVE_PAY_YEAR { get; set; }
        public string WAIVE_YEAR_MARK { get; set; }
        public string CLEAR_MARK { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public Nullable<int> RTN_AMT { get; set; }
        public string RTN_MARK { get; set; }
        public string TRANS_MARK { get; set; }
        public string NATIONALITY { get; set; }
        public string REMARK { get; set; }
        public Nullable<int> OTHR_PAY { get; set; }
        public Nullable<int> CASH_PAY_FIRST { get; set; }
        public string COMPANY { get; set; }
    }
}
