//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRW_KPI_INCENTIVE_MASTER
    {
        public string VER { get; set; }
        public string EFF_DATE { get; set; }
        public string EXP_DATE { get; set; }
        public Nullable<int> MONTH_PURP_AMT { get; set; }
        public string YYYYMM1 { get; set; }
        public string YYYYMM2 { get; set; }
        public string YYYYMM3 { get; set; }
        public string YYYYMM4 { get; set; }
        public string YYYYMM5 { get; set; }
        public string YYYYMM6 { get; set; }
        public string YYYYMM7 { get; set; }
        public string YYYYMM8 { get; set; }
        public string YYYYMM9 { get; set; }
        public string YYYYMM10 { get; set; }
        public string YYYYMM11 { get; set; }
        public string YYYYMM12 { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
    }
}
