//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRW_SALES_REVENUE_DETAILS
    {
        public string RVNU_DATE { get; set; }
        public string CA_NO { get; set; }
        public short SEQ { get; set; }
        public string YYYYMM { get; set; }
        public string KIND { get; set; }
        public string PAYMENT_TYPE { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> CHANGE { get; set; }
        public Nullable<decimal> CASH_AMT { get; set; }
        public Nullable<decimal> ERASE_AMT { get; set; }
        public string SALE_MARK { get; set; }
        public string LATE_RVNU_MARK { get; set; }
        public string PAYBACK_FLAG { get; set; }
        public string DEPOSIT_DATE { get; set; }
        public string TRANS_F210_DATE { get; set; }
    
        public virtual CRW_SALES_REVENUE_MASTER CRW_SALES_REVENUE_MASTER { get; set; }
    }
}
