//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRW_KPI_INCENTIVE_DETAILS
    {
        public string VER { get; set; }
        public string DEPT_FLT_NO { get; set; }
        public string DEPT_STN { get; set; }
        public string ARIV_STN { get; set; }
        public Nullable<int> REF_AMT { get; set; }
        public Nullable<short> PAX_CNT { get; set; }
        public Nullable<short> REF_SPH { get; set; }
        public Nullable<short> PURP_SPH { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
    }
}
