//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRW_CREDIT_CARD_POS_LOG
    {
        public string LOG_DATE { get; set; }
        public string LOG_TIME { get; set; }
        public string FUNCTION_NAME { get; set; }
        public string DEPT_DATE { get; set; }
        public string DEPT_FLT_NO { get; set; }
        public string CARD_SEQ { get; set; }
        public string IFE_SEQ { get; set; }
        public string CA_NO { get; set; }
        public string SECTOR_SEQ { get; set; }
        public string CREDIT_CARD_TYPE { get; set; }
        public string CREDIT_CARD_NO { get; set; }
        public string CREDIT_CARD_NAME { get; set; }
        public string EXP_DATE { get; set; }
        public Nullable<short> USD_AMT { get; set; }
        public Nullable<int> TWD_AMT { get; set; }
        public string DOC_NO { get; set; }
        public string ORDER_NO { get; set; }
        public string VIP_TYPE { get; set; }
        public string VIP_NO { get; set; }
        public string UG_MARK { get; set; }
        public string TRANS_CODE { get; set; }
        public string TRANS_MODE { get; set; }
        public string TRANS_DATE { get; set; }
        public string TRANS_TIME { get; set; }
        public string APPROVE_CODE { get; set; }
        public string RSPONSE_CODE { get; set; }
        public string RSPONSE_MSG { get; set; }
        public string AUTH_RETCODE { get; set; }
        public string TRANS_SEQNO { get; set; }
        public string REAUTH_MARK { get; set; }
        public string AUTH_DATE { get; set; }
        public string REMARK { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public decimal CRESEQ { get; set; }
        public string STATUS { get; set; }
        public string ONLINE_MARK { get; set; }
    }
}
