//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRW_LISTING_FEE_MASTER
    {
        public string LT_NO { get; set; }
        public string PERIOD { get; set; }
        public string VENDOR_NO { get; set; }
        public string INVOICE_TYPE { get; set; }
        public string CHARGE_TYPE { get; set; }
        public Nullable<decimal> CHARGE_AMT { get; set; }
        public string TAX_TYPE { get; set; }
        public string PAY_TYPE { get; set; }
        public string CURRENCY_TYPE { get; set; }
        public Nullable<decimal> ORA_TOT_AMT { get; set; }
        public Nullable<decimal> TOT_AMT { get; set; }
        public Nullable<decimal> EX_RATE { get; set; }
        public string INVOICE_NAME { get; set; }
        public string MAIL_ADDRESS { get; set; }
        public string REMARK { get; set; }
        public string PAY_STATUS { get; set; }
        public string PAYEE_ID { get; set; }
        public string PAY_DATE { get; set; }
        public string PAY_TIME { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public Nullable<decimal> TOT_AMT_UPD { get; set; }
    }
}
