//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRW_CREW_SALE_REVENUE
    {
        public string DEPT_DATE { get; set; }
        public string DEPT_FLT_NO { get; set; }
        public string SECTOR_SEQ { get; set; }
        public string DOC_NO { get; set; }
        public string CA_NO { get; set; }
        public Nullable<decimal> RVNU_USD { get; set; }
        public Nullable<decimal> ADJ_RVNU_USD { get; set; }
        public Nullable<int> CREDIT_CARD_USD { get; set; }
        public Nullable<int> CREDIT_CARD_TWD { get; set; }
        public Nullable<int> CASH_USD { get; set; }
        public Nullable<int> CASH_TWD { get; set; }
        public Nullable<int> CASH_HKD { get; set; }
        public Nullable<int> CASH_JPY { get; set; }
        public Nullable<int> CASH_SGD { get; set; }
        public Nullable<int> CASH_GBP { get; set; }
        public Nullable<int> CASH_ATS { get; set; }
        public Nullable<int> TRAVEL_CHK { get; set; }
        public Nullable<decimal> APPEND_AMT { get; set; }
        public string RVNU_DATE { get; set; }
        public string CLEAR_MARK { get; set; }
        public Nullable<decimal> COUPON { get; set; }
        public Nullable<decimal> APPEND_COUPON { get; set; }
        public Nullable<int> COUPON_TWD { get; set; }
        public Nullable<int> APPEND_COUPON_TWD { get; set; }
        public Nullable<decimal> FUND_AMT { get; set; }
        public string POSFALSE_MARK { get; set; }
        public string CASH_DATE { get; set; }
        public string CASH_USER { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string ORIGINAL_CA_NO { get; set; }
        public Nullable<decimal> POS_USD { get; set; }
        public string DATA_EDIT_FLAG { get; set; }
        public Nullable<decimal> POS_APPEND_AMT { get; set; }
        public Nullable<int> DISCOUNT_COUPON_TWD { get; set; }
        public Nullable<int> CASH_CNY { get; set; }
        public string TRANS_F210_DATE { get; set; }
        public Nullable<decimal> PREORD_RVNU_USD { get; set; }
    }
}
