//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRW_LISTING_FEE_TEMP
    {
        public string YEAR_MONTH { get; set; }
        public string CODE { get; set; }
        public string ENGLISH_SHORTNAME { get; set; }
        public string VENDOR_NO { get; set; }
        public string VENDOR_TYPE { get; set; }
        public string CAL_CURRENCY { get; set; }
        public Nullable<int> CAL_PRICE { get; set; }
        public string BILL_CURRENCY { get; set; }
        public Nullable<int> TOTAL_AMOUNT { get; set; }
        public string EDITPAGE_MARK { get; set; }
        public string MEMO { get; set; }
        public string IS_CLOSE { get; set; }
    }
}
