//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRW_DEBIT_NOTE_DETAILS
    {
        public string DN_NO { get; set; }
        public string SEQ { get; set; }
        public string RVNU_DATE { get; set; }
        public Nullable<decimal> SYS_AMT { get; set; }
        public Nullable<decimal> RVNU_AMT { get; set; }
        public Nullable<int> PAY_TWD { get; set; }
        public string ACCEPT_DATE { get; set; }
        public string CLEAR_MARK { get; set; }
        public string ACCT_MARK { get; set; }
        public Nullable<int> PAY_1 { get; set; }
        public Nullable<int> PAY_2 { get; set; }
        public Nullable<int> CASH_PAY { get; set; }
        public Nullable<int> WAIVE_PAY { get; set; }
        public Nullable<int> ACC_PAY { get; set; }
        public Nullable<int> UNREC_AMT { get; set; }
        public Nullable<int> WAIVE_PAY_YEAR { get; set; }
        public Nullable<int> RTN_AMT { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string DN_REMARK { get; set; }
        public string SALARY_PAY_MARK { get; set; }
        public Nullable<int> OTHR_PAY { get; set; }
        public string OTHR_ERASE_MARK { get; set; }
        public string OTHR_ERASE_REMARK { get; set; }
        public string CREW_REMARK { get; set; }
        public string ADMINISTRATION_REMARK { get; set; }
        public string PROCUREMENT_REMARK { get; set; }
        public string ERASE_NO { get; set; }
        public Nullable<int> PAY_1_UPD { get; set; }
        public Nullable<int> WAIVE_PAY_UPD { get; set; }
        public Nullable<int> CASH_PAY_UPD { get; set; }
        public string CREW_DATE { get; set; }
        public string CREW_TIME { get; set; }
        public string ADMINISTRATION_DATE { get; set; }
        public string ADMINISTRATION_TIME { get; set; }
        public string PROCUREMENT_DATE { get; set; }
        public string PROCUREMENT_TIME { get; set; }
        public Nullable<int> CASH_PAY_FIRST { get; set; }
        public string CASH_FIRST_ACCEPT_DATE { get; set; }
        public string CASHBANK_DATE { get; set; }
        public string AUT_FLAG { get; set; }
        public string CASHBANK_AUT_DATE { get; set; }
    }
}
