//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRW_CREW_SALE_ERROR
    {
        public string DEPT_DATE { get; set; }
        public string DEPT_FLT_NO { get; set; }
        public string SECTOR_SEQ { get; set; }
        public string DOC_NO { get; set; }
        public string CA_NO { get; set; }
        public Nullable<decimal> RVNU_USD { get; set; }
        public Nullable<decimal> FLIGHT_SALE_USD { get; set; }
        public Nullable<decimal> ADJ_USD { get; set; }
        public string MODI_FLAG { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
    }
}
