//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRW_CUST_PURCHASE_DETAILS
    {
        public string DEPT_DATE { get; set; }
        public string DEPT_FLT_NO { get; set; }
        public string DOC_NO { get; set; }
        public string SECTOR_SEQ { get; set; }
        public string RECIPT_NO { get; set; }
        public string CODE { get; set; }
        public Nullable<decimal> SALE_PRICE { get; set; }
        public Nullable<decimal> VIP_PRICE { get; set; }
        public Nullable<short> SALE_QTY { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public Nullable<decimal> SOLD_UNIT_PRICE { get; set; }
        public string REFUND_NO { get; set; }
        public Nullable<decimal> SUB_TOTAL { get; set; }
        public Nullable<decimal> SUB_TOTAL_USD { get; set; }
        public Nullable<short> RTN_QTY { get; set; }
        public Nullable<decimal> RTN_AMT { get; set; }
        public string EXPIRE_DATE { get; set; }
        public string DISCOUNT_TYPE { get; set; }
        public Nullable<short> TRANS_SEQ { get; set; }
    }
}
