//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUB_MYB2B_DATALINK
    {
        public string BANK_ACCOUNT_NO { get; set; }
        public string TRANS_DATE { get; set; }
        public string TRANS_SEQ_NO { get; set; }
        public string TRANS_ID_NO { get; set; }
        public string CHECK_NO { get; set; }
        public string DRCR { get; set; }
        public Nullable<long> TRANS_AMT { get; set; }
        public Nullable<long> BAL_AMT { get; set; }
        public string PSEUDO_ACCOUN_NO { get; set; }
        public string TRANS_MACH_NO { get; set; }
        public string TRANS_DESC { get; set; }
        public string BANK_ID { get; set; }
        public string ACCOUNT_NAME { get; set; }
        public string ACCOUNT_NO { get; set; }
        public string TRANS_TIME { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
    }
}
