//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMILY_PRE_ORDER
    {
        public string ORDER_NO { get; set; }
        public string ORDER_DATE { get; set; }
        public string ORDER_TIME { get; set; }
        public string CARD_FUND_DATE { get; set; }
        public string GL_DATE { get; set; }
        public string TRANS_DATE { get; set; }
        public string CANCEL_DATE { get; set; }
        public string CUST_NBR { get; set; }
        public string FFP_CARD_TYPE { get; set; }
        public string CUST_TITLE { get; set; }
        public string CUST_FIRSTNAME { get; set; }
        public string CUST_LASTNAME { get; set; }
        public string CUST_EMAIL { get; set; }
        public string CUST_PASSPORT_NO { get; set; }
        public string CUST_TEL_H { get; set; }
        public string CUST_TEL_M { get; set; }
        public string CUST_TEL_OTH { get; set; }
        public string CUST_LANGUAGE { get; set; }
        public string PNR { get; set; }
        public string FLT_NO { get; set; }
        public string SEGMENT_NO { get; set; }
        public string DEPT_STN { get; set; }
        public string DEPT_STN_DESC { get; set; }
        public string DEPT_DATE { get; set; }
        public string DEPT_TIME { get; set; }
        public string ARIV_STN { get; set; }
        public string ARIV_STN_DESC { get; set; }
        public string ARIV_DATE { get; set; }
        public string ARIV_TIME { get; set; }
        public string BASE_DEPT_STN { get; set; }
        public string BASE_FLT_NO { get; set; }
        public string BASE_DEPT_DATE { get; set; }
        public string TRANS_NO { get; set; }
        public string REMARK { get; set; }
        public Nullable<decimal> MILEAGE_ORDER { get; set; }
        public Nullable<decimal> MILEAGE_ITEM { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<decimal> TTL_AMT_ORI { get; set; }
        public Nullable<decimal> TTL_AMT_ORI_TWD { get; set; }
        public Nullable<decimal> TTL_AMT_ORI_USD { get; set; }
        public Nullable<decimal> DTLS_TTL_AMT { get; set; }
        public Nullable<decimal> DTLS_TTL_AMT_TWD { get; set; }
        public Nullable<decimal> DTLS_TTL_AMT_USD { get; set; }
        public Nullable<decimal> RCV_AMT { get; set; }
        public Nullable<decimal> RCV_AMT_TWD { get; set; }
        public Nullable<decimal> RCV_AMT_USD { get; set; }
        public Nullable<decimal> WEB_DISC { get; set; }
        public Nullable<decimal> WEB_DISC_AMT { get; set; }
        public Nullable<decimal> WEB_DISC_AMT_TWD { get; set; }
        public Nullable<decimal> WEB_DISC_AMT_USD { get; set; }
        public Nullable<decimal> ACT_RCV_AMT { get; set; }
        public Nullable<int> ACT_RCV_AMT_TWD { get; set; }
        public Nullable<decimal> ACT_RCV_AMT_USD { get; set; }
        public string PAY_CURRENCY_FLAG { get; set; }
        public string PAY_ITEM_FLAG { get; set; }
        public string ALLOW_INFLT_DISC_IND { get; set; }
        public Nullable<decimal> INFLT_DISC { get; set; }
        public string INFLT_DISC_CURRENCY { get; set; }
        public Nullable<decimal> INFLT_DISC_AMT { get; set; }
        public Nullable<decimal> INFLT_DISC_AMT_TWD { get; set; }
        public Nullable<decimal> INFLT_DISC_AMT_USD { get; set; }
        public string TRANS_CAROUSEL_FLAG { get; set; }
        public string RTN_FLAG { get; set; }
        public string ORIGIN_NO { get; set; }
        public Nullable<decimal> ORI_SYS_RTN_AMT { get; set; }
        public Nullable<decimal> ORI_SYS_RTN_AMT_TWD { get; set; }
        public Nullable<decimal> ORI_SYS_RTN_AMT_USD { get; set; }
        public Nullable<decimal> ACT_RTN_AMT { get; set; }
        public Nullable<decimal> ACT_RTN_AMT_TWD { get; set; }
        public Nullable<decimal> ACT_RTN_AMT_USD { get; set; }
        public Nullable<decimal> ACT_RTN_MILEAGE { get; set; }
        public Nullable<decimal> ORI_RTN_MILEAGE_ITEM { get; set; }
        public Nullable<decimal> ORI_RTN_MILEAGE_ORDER { get; set; }
        public string STATUS { get; set; }
        public string PNR_CANCEL_FLAG { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string VIP_MARK { get; set; }
        public string CONFIRM_DATE { get; set; }
        public string REASON_TYPE { get; set; }
        public string ORDER_FIRSTNAME { get; set; }
        public string ORDER_LASTNAME { get; set; }
        public string ORDER_SEX { get; set; }
        public string CUST_SEX { get; set; }
        public string AGENT_GRP_NAME { get; set; }
        public string AGREE_DATETIME { get; set; }
        public string CANCEL_FAIL_FLAG { get; set; }
        public string GROUP_FLAG { get; set; }
        public string DOC_NO { get; set; }
        public string OLD_PNR { get; set; }
        public string IEDF_EDIT_FLAG { get; set; }
        public string APP_ORDER_MARK { get; set; }
    }
}
