//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_STOCK_MONTH_END_06
    {
        public string BACKUP_PERIOD { get; set; }
        public string STORE_NO { get; set; }
        public string CODE { get; set; }
        public Nullable<decimal> CURR_QTY { get; set; }
        public Nullable<decimal> CURR_UNIT_PRICE { get; set; }
        public Nullable<decimal> CURR_AMT { get; set; }
        public Nullable<decimal> CURR_RCV_QTY { get; set; }
        public Nullable<decimal> CURR_RCV_AMT { get; set; }
        public Nullable<decimal> CURR_ISU_QTY { get; set; }
        public Nullable<decimal> CURR_ISU_AMT { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
    }
}
