//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_TRANS_DETAILS
    {
        public string TRANS_NO { get; set; }
        public short TRANS_SEQ { get; set; }
        public string CODE { get; set; }
        public Nullable<decimal> TRANS_QTY { get; set; }
        public Nullable<int> TRANS_AMT { get; set; }
        public Nullable<short> PURCHASE_SEQ { get; set; }
        public Nullable<int> ACCT_SEQ { get; set; }
        public string EXPIRE_DATE { get; set; }
        public string IS_EXPIRE_CODE { get; set; }
        public Nullable<int> EXAMS_QTY { get; set; }
        public string QUALIFIED_FLAG { get; set; }
        public string ORIGINAL_TRANS_NO { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public Nullable<decimal> ORIGINAL_TRANS_AMT { get; set; }
        public string SUPPLY_MODE_FLAG { get; set; }
        public Nullable<decimal> UNIFORM_COST { get; set; }
        public Nullable<short> CUSTOMS_ITEM_SEQ { get; set; }
    }
}
