//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_PACKING_DETAILS
    {
        public string TRANS_NO { get; set; }
        public short TRANS_SEQ { get; set; }
        public string CODE { get; set; }
        public Nullable<int> TRANS_QTY { get; set; }
        public Nullable<decimal> DIMENSION_L { get; set; }
        public Nullable<decimal> DIMENSION_W { get; set; }
        public Nullable<decimal> DIMENSION_H { get; set; }
        public Nullable<decimal> GROSS_WT { get; set; }
        public Nullable<short> CNT_NO1 { get; set; }
        public Nullable<short> CNT_NO2 { get; set; }
        public Nullable<decimal> CURR_UNIT_PRICE { get; set; }
        public Nullable<short> CNT_QTY { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
    
        public virtual INV_PACKING_MASTER INV_PACKING_MASTER { get; set; }
    }
}
