//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_TRANS_MASTER
    {
        public string TRANS_NO { get; set; }
        public string STATUS { get; set; }
        public string DEPARTMENT_NO { get; set; }
        public string CARD_ID { get; set; }
        public string CONFIRM_DATE { get; set; }
        public string TRANS_DATE { get; set; }
        public string STORE_FROM { get; set; }
        public string STORE_TO { get; set; }
        public string AR_SE { get; set; }
        public string ISSUE_TYPE { get; set; }
        public string REF1 { get; set; }
        public string REF2 { get; set; }
        public string PURCHASE_NO { get; set; }
        public string CUSTOMS_MARK { get; set; }
        public string USER_ID { get; set; }
        public Nullable<decimal> ESTI { get; set; }
        public string REMARK { get; set; }
        public string DEPT_APPROVE { get; set; }
        public string ADMIN_APPROVE { get; set; }
        public string APPLICANT { get; set; }
        public string G_TYPE { get; set; }
        public string DEPT_USER { get; set; }
        public string ADMIN_USER { get; set; }
        public string CONFIRM2_DATE { get; set; }
        public string CONFIRM_USER { get; set; }
        public string CONFIRM2_USER { get; set; }
        public string SHEET_NO1 { get; set; }
        public string SHEET_NO2 { get; set; }
        public string APPLY_NO1 { get; set; }
        public string APPLY_NO2 { get; set; }
        public string CUSTOMS_NO1 { get; set; }
        public string CUSTOMS_NO2 { get; set; }
        public string CUSTOMS_DATE { get; set; }
        public string VENDOR_NO { get; set; }
        public string PACKING_STATUS { get; set; }
        public string TRANS_FLAG { get; set; }
        public string REQ_DATE { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string REMARK2 { get; set; }
        public string DEFAULT_LOCATION { get; set; }
        public string OUTSTOCK_RECORD { get; set; }
        public string BOX_FLAG { get; set; }
        public string AP_NO { get; set; }
        public string AP_ERASE_REMARK { get; set; }
        public string DEPARTMENT_SUB_NO { get; set; }
        public string OUT_MONTH { get; set; }
        public string OUT_STN { get; set; }
    }
}
