//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_ORDER_DETAILS
    {
        public string ORDER_NO { get; set; }
        public Nullable<short> ORDER_SEQ { get; set; }
        public string CODE { get; set; }
        public string CHK_CODE { get; set; }
        public string ORDER_UNIT { get; set; }
        public Nullable<decimal> ORDER_QTY { get; set; }
        public Nullable<decimal> TOT_QTY { get; set; }
        public Nullable<decimal> CHK_QTY { get; set; }
        public Nullable<decimal> CHK_TOT_QTY { get; set; }
        public Nullable<decimal> H_QTY { get; set; }
        public Nullable<decimal> H_TOT_QTY { get; set; }
        public string BONDED { get; set; }
        public Nullable<short> CAR { get; set; }
        public string MARK { get; set; }
        public string CHK_FLAG { get; set; }
        public string CHK_USER_ID { get; set; }
        public string STATUS { get; set; }
        public string MENO { get; set; }
        public Nullable<int> SAFE_QTY { get; set; }
        public Nullable<int> STOCK_QTY { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
    }
}
