//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_CSGMT_STOCK_MONTH_END_0921
    {
        public string PERIOD { get; set; }
        public string CODE { get; set; }
        public string CLASS { get; set; }
        public string VENDOR_NO { get; set; }
        public Nullable<decimal> RCV_QTY { get; set; }
        public Nullable<decimal> RCV_AMT { get; set; }
        public Nullable<decimal> RTN_QTY { get; set; }
        public Nullable<decimal> RTN_AMT { get; set; }
        public Nullable<decimal> PAID_SALE_QTY { get; set; }
        public Nullable<decimal> PAID_SALE_AMT { get; set; }
        public Nullable<decimal> ISU_QTY_2146AD { get; set; }
        public Nullable<decimal> ISU_AMT_2146AD { get; set; }
        public Nullable<decimal> ISU_QTY_OTHR { get; set; }
        public Nullable<decimal> ISU_AMT_OTHR { get; set; }
        public string DECIDE_FLAG { get; set; }
        public string DECIDE_DATE { get; set; }
        public string TRANS_FLAG { get; set; }
        public string TRANS_DATE { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
    }
}
