//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_SHORT_DOC
    {
        public string SHORT_NO { get; set; }
        public string CODE { get; set; }
        public string VENDOR_NO { get; set; }
        public string PURCHASE_NO { get; set; }
        public string SHIP_COMPANY { get; set; }
        public string BL_NO { get; set; }
        public string INSTORE_DATE { get; set; }
        public Nullable<int> INSTORE_QTY { get; set; }
        public string SHORT_DATE { get; set; }
        public Nullable<int> SHORT_QTY { get; set; }
        public string SHORT_REASON { get; set; }
        public string H_NO { get; set; }
        public string G_NO { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
        public string PROCESS_TYPE { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string STORE_NO { get; set; }
    }
}
