//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_INVENTORY_20150302
    {
        public string STORE_NO { get; set; }
        public string CODE { get; set; }
        public Nullable<decimal> CURR_QTY { get; set; }
        public Nullable<decimal> PO_ONWAY_QTY { get; set; }
        public Nullable<decimal> PREN_QTY { get; set; }
        public Nullable<decimal> SAFE_QTY { get; set; }
        public Nullable<decimal> MAX_QTY { get; set; }
        public string LAST_RCV_DATE { get; set; }
        public string LAST_ISU_DATE { get; set; }
        public Nullable<decimal> H_ONWAY_QTY { get; set; }
        public Nullable<decimal> ALLOT_COEFFICIENT { get; set; }
        public Nullable<decimal> ALLOT_QTY { get; set; }
        public string LOCATION { get; set; }
        public Nullable<int> CONSUMPTION_QTY { get; set; }
        public string CONSUMPTION_MONTH_START { get; set; }
        public string CONSUMPTION_MONTH_END { get; set; }
        public string CONSUMPTION_PERIOD_DAYS { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string SAFE_QTY_FLAG { get; set; }
        public Nullable<decimal> REF_QTY { get; set; }
    }
}
