//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_WITH_PALLET_MANG_TO_TEMG
    {
        public int SEQ { get; set; }
        public string PALLET_ID { get; set; }
        public string CODE { get; set; }
        public string DEPARTMENT_NO { get; set; }
        public string TRANS_NO { get; set; }
        public int COEFFICIENT { get; set; }
        public string STORE_UNIT { get; set; }
        public string PACKAGE_UNIT { get; set; }
        public string STORE_NO { get; set; }
        public string STORAGE_DATE { get; set; }
        public Nullable<int> STORAGE_QTY { get; set; }
        public string EXPIRE_DATE { get; set; }
        public string PALLET_LOCATION { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string QUALIFIED_FLAG { get; set; }
    }
}
