//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCS_OUTSTOCK_RECORD
    {
        public string TRANS_NO { get; set; }
        public string SEQ { get; set; }
        public string PALLET_ID { get; set; }
        public string CODE { get; set; }
        public string STORAGE_DATE { get; set; }
        public string EXPIRE_DATE { get; set; }
        public short COEFFICIENT { get; set; }
        public Nullable<int> OUT_QTY { get; set; }
        public Nullable<int> PUT_IN_QTY { get; set; }
        public string OUT_FLOOR { get; set; }
        public string PALLET_LOCATION { get; set; }
    }
}
