//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCS_QUEUE_PALLET_LOCATION
    {
        public string PALLET_STATUS { get; set; }
        public string PALLET_ID { get; set; }
        public string PALLET_LOCATION { get; set; }
        public string CODE { get; set; }
        public Nullable<int> STORAGE_QTY { get; set; }
        public string EXPIRE_DATE { get; set; }
        public string INOUT_TIME { get; set; }
        public Nullable<int> COEFFICIENT { get; set; }
        public int SEQ { get; set; }
        public string REMARK { get; set; }
        public string QUALIFIED_FLAG { get; set; }
    }
}
