//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCS_MESSAGE_LOG_SMAS
    {
        public string MESSAGE_FROM { get; set; }
        public string TRANS_DATETIME { get; set; }
        public int SEQUENCE_NO { get; set; }
        public string MESSAGE_TYPE { get; set; }
        public string MESSAGE_STATUS { get; set; }
        public string SEQ { get; set; }
        public string PALLET_ID { get; set; }
        public string OVERWRITE { get; set; }
        public string PRIORITY { get; set; }
        public string ACTIVATION_TIME { get; set; }
        public string RETRIEVAL_DESTINATION { get; set; }
        public string CODE { get; set; }
        public Nullable<int> TRANS_QTY { get; set; }
        public string FREQUENCY_CLASS { get; set; }
        public string STORAGE_CLASS { get; set; }
        public string AISLE_NO { get; set; }
        public string AISLE_STATUS { get; set; }
        public Nullable<short> HEIGHT_CLASS { get; set; }
        public Nullable<short> WEIGHT { get; set; }
        public string STORAGE_DATE { get; set; }
        public string TRANSACTION_TYPE { get; set; }
        public string SOURCE_LOCATION { get; set; }
        public string DESTINATION_LOCATION { get; set; }
        public string MOVEMENT_STATUS { get; set; }
        public string TRANS_NO { get; set; }
        public string DEPARTMENT_NO { get; set; }
        public Nullable<int> COEFFICIENT { get; set; }
        public string STORE_UNIT { get; set; }
        public string PACKAGE_UNIT { get; set; }
        public string STORE_NO { get; set; }
        public string EXPIRE_DATE { get; set; }
        public string PUT_IN_AGAIN { get; set; }
        public string MARK { get; set; }
        public Nullable<int> PUT_IN_QTY { get; set; }
        public string PUT_TO_TEMP { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string REMARK { get; set; }
        public string QUALIFIED_FLAG { get; set; }
    }
}
