//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCS_WH_MATERIAL
    {
        public string CODE { get; set; }
        public string STORAGE_CLASS { get; set; }
        public string FREQUENCY_CLASS { get; set; }
        public string DEFAULT_LOCATION { get; set; }
        public string HEIGHT { get; set; }
        public string MERGE_MARK { get; set; }
        public string RECORD_STORAGE { get; set; }
        public Nullable<short> BOTTOM { get; set; }
        public Nullable<short> LEVEL1 { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
    }
}
