//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_BAS
    {
        public string FILE_NAME { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string FIELD_NAME_01 { get; set; }
        public string FIELD_DATA_01 { get; set; }
        public string FIELD_NAME_02 { get; set; }
        public string FIELD_DATA_02 { get; set; }
        public string FIELD_NAME_03 { get; set; }
        public string FIELD_DATA_03 { get; set; }
        public string FIELD_NAME_04 { get; set; }
        public string FIELD_DATA_04 { get; set; }
        public string FIELD_NAME_05 { get; set; }
        public string FIELD_DATA_05 { get; set; }
        public string FIELD_NAME_06 { get; set; }
        public string FIELD_DATA_06 { get; set; }
        public string FIELD_NAME_07 { get; set; }
        public string FIELD_DATA_07 { get; set; }
        public string FIELD_NAME_08 { get; set; }
        public string FIELD_DATA_08 { get; set; }
        public string FIELD_NAME_09 { get; set; }
        public string FIELD_DATA_09 { get; set; }
        public string FIELD_NAME_10 { get; set; }
        public string FIELD_DATA_10 { get; set; }
        public string FIELD_NAME_11 { get; set; }
        public string FIELD_DATA_11 { get; set; }
        public string FIELD_NAME_12 { get; set; }
        public string FIELD_DATA_12 { get; set; }
        public string FIELD_NAME_13 { get; set; }
        public string FIELD_DATA_13 { get; set; }
        public string FIELD_NAME_14 { get; set; }
        public string FIELD_DATA_14 { get; set; }
        public string FIELD_NAME_15 { get; set; }
        public string FIELD_DATA_15 { get; set; }
        public string FIELD_NAME_16 { get; set; }
        public string FIELD_DATA_16 { get; set; }
        public string FIELD_NAME_17 { get; set; }
        public string FIELD_DATA_17 { get; set; }
        public string FIELD_NAME_18 { get; set; }
        public string FIELD_DATA_18 { get; set; }
        public string FIELD_NAME_19 { get; set; }
        public string FIELD_DATA_19 { get; set; }
        public string FIELD_NAME_20 { get; set; }
        public string FIELD_DATA_20 { get; set; }
    }
}
