//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGT_JOB_LOG_FAIL
    {
        public string SRC_MACHINE { get; set; }
        public string RUN_ID { get; set; }
        public string JOB_ID { get; set; }
        public string JOB_NAME { get; set; }
        public string DLL_NAME { get; set; }
        public string CFG_DATE { get; set; }
        public string CFG_TIME { get; set; }
        public string EXEC_DATE { get; set; }
        public string EXEC_TIME { get; set; }
        public string FINISH_DATE { get; set; }
        public string FINISH_TIME { get; set; }
        public Nullable<short> RETRY { get; set; }
        public string STATUS { get; set; }
        public string MESSAGE { get; set; }
    }
}
