//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class NSP_FLIGHT_SUMMARY
    {
        public string DEPT_DATE { get; set; }
        public string FLT_NO { get; set; }
        public string FLT_SEQ { get; set; }
        public string NEWS_CODE { get; set; }
        public string AC_TYPE { get; set; }
        public string DEPT_TIME { get; set; }
        public string DEPT_STN { get; set; }
        public string ARIV_STN { get; set; }
        public string DEPT_FLT_NO { get; set; }
        public string BASE_DATE { get; set; }
        public string SVC_TYPE { get; set; }
        public Nullable<short> PAX_CNT { get; set; }
        public Nullable<short> PAX_RATIO { get; set; }
        public Nullable<short> NEWS_QTY { get; set; }
        public Nullable<decimal> AM_RATIO { get; set; }
        public Nullable<decimal> PM_RATIO { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string FLT_REGION { get; set; }
        public string BASE_DEPT_STN { get; set; }
        public string TRANS_NO { get; set; }
        public string MODIFY_MARK { get; set; }
        public string APPROVE_STATUS { get; set; }
        public string MODIFY_MODE { get; set; }
        public string AUT_DATE { get; set; }
        public string AUT_FLAG { get; set; }
    }
}
