//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class NSP_MAGAZINE_ESTIMATE
    {
        public string YEAR { get; set; }
        public string MONTH { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string CURRENCY { get; set; }
        public string YYMM_MAG_S { get; set; }
        public string YYMM_MAG_E { get; set; }
        public string YYMM_OMAG_S { get; set; }
        public string YYMM_OMAG_E { get; set; }
    }
}
