//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class NSP_MAGAZINE_MASTER
    {
        public string MAZ_YEAR { get; set; }
        public string MAZ_NO { get; set; }
        public string MAZ_CNAME { get; set; }
        public string MAZ_ENAME { get; set; }
        public Nullable<decimal> MAX_QTY { get; set; }
        public Nullable<decimal> MIN_QTY { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
        public string MAZ_CURY { get; set; }
        public string PUBLISH_PERIOD { get; set; }
        public string START_MONTH { get; set; }
        public string REMARK { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
    }
}
