//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUT_CONSUMPTION_ANAS_SETTING
    {
        public string STORE_NO { get; set; }
        public string CODE { get; set; }
        public string CALC_TYPE { get; set; }
        public string EXTRA_LOAD_MARK { get; set; }
        public string SPCL_RATIO_MARK { get; set; }
        public string GROUP_CD { get; set; }
        public Nullable<decimal> PROFIT_DIFF_RATIO { get; set; }
        public Nullable<decimal> LOSS_DIFF_RATIO { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string FLAG { get; set; }
    }
}
