//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUT_ESC1_STOCK_FLIGHT
    {
        public string STOCK_DATETIME { get; set; }
        public string FLIGHT_NO { get; set; }
        public string AC_NO { get; set; }
        public string AC_TYPE { get; set; }
        public string ETD_TIME { get; set; }
        public string ATD_TIME { get; set; }
        public string ETA_TIME { get; set; }
        public string ATA_TIME { get; set; }
        public string DEPT_STN { get; set; }
        public string ARIV_STN { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
    }
}
