//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUT_CONSUMPTION_CALCULATE_ESC1
    {
        public string PERIOD { get; set; }
        public string STORE_NO { get; set; }
        public string CODE { get; set; }
        public string CONSUMPTION_IND { get; set; }
        public string CALC_TYPE { get; set; }
        public string EXTRA_LOAD_MARK { get; set; }
        public string SPCL_RATIO_MARK { get; set; }
        public string GROUP_CD { get; set; }
        public Nullable<decimal> PROFIT_RATIO { get; set; }
        public Nullable<decimal> LOSS_RATIO { get; set; }
        public Nullable<int> CONS_QTY { get; set; }
        public Nullable<short> DAMAGE_QTY { get; set; }
        public Nullable<int> TTL_ONBOARD_PAX { get; set; }
        public Nullable<int> TTL_FLT_CNT { get; set; }
        public Nullable<int> TTL_LOAD_QTY { get; set; }
        public Nullable<int> THEORY_CONS_QTY { get; set; }
        public Nullable<int> THEORY_CONS_QTY_UPD { get; set; }
        public Nullable<decimal> AVG_CONS_QTY { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
    }
}
