//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUTSTATION_MAST_SYD
    {
        public string PERIOD { get; set; }
        public string STORE_NO { get; set; }
        public string G_NO { get; set; }
        public string C_NO { get; set; }
        public string DEPT { get; set; }
        public string TRANS_FLAG { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string TRN_ID { get; set; }
        public string TRN_DATE { get; set; }
        public string TRN_TIME { get; set; }
    }
}
