//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUTSTATION_TAIL_SYD
    {
        public string PERIOD { get; set; }
        public string STORE_NO { get; set; }
        public string CODE { get; set; }
        public Nullable<int> OPEN_QTY { get; set; }
        public Nullable<int> CLOSE_QTY { get; set; }
        public Nullable<int> TRANS_IN_QTY { get; set; }
        public Nullable<int> TRANS_OUT_QTY { get; set; }
        public Nullable<int> ON_WAY_QTY { get; set; }
        public Nullable<int> TRANS_QTY { get; set; }
        public Nullable<int> A3_QTY { get; set; }
        public Nullable<int> RECEIVE_QTY { get; set; }
        public Nullable<int> TRANS_IN { get; set; }
        public Nullable<int> TRANS_OUT { get; set; }
        public Nullable<int> PREP_QTY { get; set; }
        public Nullable<int> STORE_QTY { get; set; }
        public Nullable<int> REQUEST_QTY { get; set; }
        public string TRANS_LOCK { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
    }
}
