//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_ORDER_CHECK_LOG
    {
        public string LOG_ID { get; set; }
        public string ORDER_NO { get; set; }
        public string ORDER_TYPE { get; set; }
        public string JOB_NAME { get; set; }
        public string CODE { get; set; }
        public Nullable<decimal> BEFORE_PREN_QTY { get; set; }
        public Nullable<decimal> AFTER_PREN_QTY { get; set; }
        public Nullable<decimal> ORDER_QTY { get; set; }
        public Nullable<decimal> TRANS_QTY { get; set; }
        public string MESSAGE { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
    }
}
