//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_FFP_MILEAGE
    {
        public string ORDER_NO { get; set; }
        public string CUST_NBR { get; set; }
        public string CUST_FIRSTNAME { get; set; }
        public string CUST_LASTNAME { get; set; }
        public string FLT_DATE { get; set; }
        public string FLT_NBR { get; set; }
        public string FLT_SECTOR { get; set; }
        public string PNR_REF { get; set; }
        public string BONUS_CODE { get; set; }
        public string BONUS_DESC { get; set; }
        public Nullable<decimal> MILEAGE { get; set; }
        public string REMARK { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
    }
}
