//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_FLIGHT_CHANGE
    {
        public string ORDER_NO { get; set; }
        public string VER { get; set; }
        public string ORI_BASE_DEPT_DATE { get; set; }
        public string ORI_BASE_FLT_NO { get; set; }
        public string ORI_DEPT_DATE { get; set; }
        public string ORI_FLT_NO { get; set; }
        public string ORI_PNR { get; set; }
        public string ORI_DEPT_TIME { get; set; }
        public string ORI_ARIV_DATE { get; set; }
        public string ORI_ARIV_TIME { get; set; }
        public string ORI_DEPT_STN { get; set; }
        public string ORI_ARIV_STN { get; set; }
        public string ORI_BASE_DEPT_STN { get; set; }
        public string NEW_BASE_DEPT_DATE { get; set; }
        public string NEW_BASE_FLT_NO { get; set; }
        public string NEW_DEPT_DATE { get; set; }
        public string NEW_FLT_NO { get; set; }
        public string NEW_PNR { get; set; }
        public string NEW_DEPT_TIME { get; set; }
        public string NEW_ARIV_DATE { get; set; }
        public string NEW_ARIV_TIME { get; set; }
        public string NEW_DEPT_STN { get; set; }
        public string NEW_ARIV_STN { get; set; }
        public string NEW_BASE_DEPT_STN { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
    }
}
