//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_PREORDER_MATERIAL
    {
        public string CODE { get; set; }
        public string VENDOR_NO { get; set; }
        public string NAME_CHINESE { get; set; }
        public string NAME_ENGLISH { get; set; }
        public string PROD_INFO_CHINESE { get; set; }
        public string PROD_INFO_ENGLISH { get; set; }
        public string PROD_SPEC_CHINESE { get; set; }
        public string PROD_SPEC_ENGLISH { get; set; }
        public string STORE_UNIT { get; set; }
        public Nullable<int> COEFFICIENT { get; set; }
        public Nullable<int> MAX_ORDER_QTY { get; set; }
        public Nullable<int> MIN_ORDER_QTY { get; set; }
        public byte[] IMAGE { get; set; }
        public Nullable<decimal> BRAND_ID { get; set; }
        public string PREONLY_FLAG { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string SP_DESC_CHINESE { get; set; }
        public string SP_DESC_ENGLISH { get; set; }
    }
}
