//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_ORDER_PROMOTION_VIP
    {
        public string ORDER_NO { get; set; }
        public string PMT_ID { get; set; }
        public Nullable<decimal> INFLT_DISC { get; set; }
        public string INFLT_DISC_CURRENCY { get; set; }
        public Nullable<decimal> INFLT_DISC_AMT { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string INFLT_DISC_IND { get; set; }
    }
}
