//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_ORDER_MILEAGE_LOG
    {
        public string LOG_ID { get; set; }
        public string ORDER_NO { get; set; }
        public string FFP_CARD_NO { get; set; }
        public string MILEAGE_CHG_TYPE { get; set; }
        public string WBS_NAME { get; set; }
        public string WBS_INPUT { get; set; }
        public string WBS_OUTPUT { get; set; }
        public string FFP_DEDUCT_CERTIFICATE { get; set; }
        public string ERR_MSG { get; set; }
        public string EXECUTE_STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string RTN_NO { get; set; }
        public string NEW_DEDUCT_CERTIFICATE { get; set; }
        public string PROG_NAME { get; set; }
        public Nullable<decimal> MILEAGE_TOTAL_EXC { get; set; }
    }
}
