//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_PROMOTION_TEMP_PAYMENT
    {
        public int TEMP_SEQ { get; set; }
        public string ORDER_NO { get; set; }
        public string PAY_SEQ { get; set; }
        public string PAY_TYPE { get; set; }
        public Nullable<decimal> PAY_AMT { get; set; }
        public Nullable<decimal> PAY_AMT_USD { get; set; }
        public Nullable<int> PAY_AMT_TWD { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
    }
}
