//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_ORDER_MASTER_IEDF_MAPPING
    {
        public string TRANSDATETIME { get; set; }
        public string ORDER_NO { get; set; }
        public string STATUS { get; set; }
        public string CUST_FIRSTNAME { get; set; }
        public string CUST_LASTNAME { get; set; }
        public string PNR { get; set; }
        public string FLT_NO { get; set; }
        public string DEPT_DATE { get; set; }
        public string DEPT_STN { get; set; }
        public string ARIV_STN { get; set; }
        public string MAPPING_IND { get; set; }
        public string PAX_NO { get; set; }
        public string ST_NO { get; set; }
        public string OT_NO { get; set; }
        public string ADD_IEDF { get; set; }
        public string CANX_IEDF { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
    }
}
