//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_GROUP_INFORMATION
    {
        public string FLT_NO { get; set; }
        public string FLT_DATE { get; set; }
        public string DEPT_STN { get; set; }
        public string ARIV_STN { get; set; }
        public string SSR { get; set; }
        public string PNR { get; set; }
        public string GRP_NAME { get; set; }
        public string CRT_DATE { get; set; }
        public string TRN_DATE { get; set; }
        public string TRANS_DATE { get; set; }
        public string TRANS_TIME { get; set; }
    }
}
