//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_ORDER_DETAILS_0703
    {
        public string ORDER_NO { get; set; }
        public decimal ORDER_SEQ { get; set; }
        public string CODE { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
        public Nullable<decimal> UNIT_PRICE_TWD { get; set; }
        public Nullable<decimal> UNIT_PRICE_USD { get; set; }
        public Nullable<decimal> UNIT_PRICE_DISC { get; set; }
        public Nullable<decimal> UNIT_PRICE_DISC_TWD { get; set; }
        public Nullable<decimal> UNIT_PRICE_DISC_USD { get; set; }
        public Nullable<decimal> ORDER_QTY { get; set; }
        public string DISC_FLAG { get; set; }
        public Nullable<decimal> DISC { get; set; }
        public Nullable<decimal> SUB_TOTAL { get; set; }
        public Nullable<decimal> SUB_TOTAL_TWD { get; set; }
        public Nullable<decimal> SUB_TOTAL_USD { get; set; }
        public Nullable<decimal> UNIT_MILEAGE { get; set; }
        public Nullable<decimal> SUB_MILEAGE { get; set; }
        public string PMT_ID { get; set; }
        public string CONSIGNED { get; set; }
        public string RELATED_CODE { get; set; }
        public string INFLT_PMT_ID { get; set; }
        public Nullable<decimal> INFLT_DISC { get; set; }
        public string INFLT_DISC_CURRENCY { get; set; }
        public Nullable<decimal> INFLT_DISC_AMT { get; set; }
        public Nullable<decimal> INFLT_DISC_AMT_TWD { get; set; }
        public Nullable<decimal> INFLT_DISC_AMT_USD { get; set; }
        public Nullable<decimal> INFLT_UNIT_PRICE { get; set; }
        public Nullable<decimal> INFLT_UNIT_PRICE_TWD { get; set; }
        public Nullable<decimal> INFLT_UNIT_PRICE_USD { get; set; }
        public Nullable<decimal> INFLT_SUB_TOTAL { get; set; }
        public Nullable<decimal> INFLT_SUB_TOTAL_TWD { get; set; }
        public Nullable<decimal> INFLT_SUB_TOTAL_USD { get; set; }
        public Nullable<decimal> RTN_QTY { get; set; }
        public Nullable<decimal> RTN_MILEAGE { get; set; }
        public Nullable<decimal> RTN_AMT { get; set; }
        public Nullable<decimal> RTN_AMT_TWD { get; set; }
        public Nullable<decimal> RTN_AMT_USD { get; set; }
        public Nullable<decimal> SUB_TOTAL_CURR { get; set; }
        public Nullable<decimal> SUB_TOTAL_CURR_TWD { get; set; }
        public Nullable<decimal> SUB_TOTAL_CURR_USD { get; set; }
        public string EXPIRE_DATE { get; set; }
        public Nullable<short> ORDER_QTY_UPD { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string SPCL_DISC_MARK { get; set; }
    }
}
