//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_HBS_COMMAND
    {
        public string CMD_DEPT_DATE { get; set; }
        public string CMD_DEPT_TIME { get; set; }
        public string CMD_FLT_NO { get; set; }
        public string CMD_DEPT_STN { get; set; }
        public string CMD_ARIV_STN { get; set; }
        public string CMD_DDMMM { get; set; }
        public int HHC_CMD_SEQ { get; set; }
        public string TRANS_DATETIME { get; set; }
        public string PRE_ORDER_IND { get; set; }
        public string STATUS { get; set; }
        public string DEPT_DATE { get; set; }
        public string FLT_NO { get; set; }
        public string DEPT_STN { get; set; }
        public string ARIV_STN { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
    }
}
