//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_KM_MESSAGE
    {
        public int KM_CMD_SEQ { get; set; }
        public string MSG_TYPE { get; set; }
        public string ORDER_NO { get; set; }
        public string OLD_PNR { get; set; }
        public string NEW_PNR { get; set; }
        public string OLD_FLT_NO { get; set; }
        public string NEW_FLT_NO { get; set; }
        public string OLD_DEPT_STN { get; set; }
        public string NEW_DEPT_STN { get; set; }
        public string OLD_DEPT_DATE { get; set; }
        public string NEW_DEPT_DATE { get; set; }
        public string OLD_ARIV_STN { get; set; }
        public string NEW_ARIV_STN { get; set; }
        public string OLD_CUST_NAME { get; set; }
        public string NEW_CUST_NAME { get; set; }
        public string KM_MQ_TEXT { get; set; }
        public string MSG_RCV_DATE { get; set; }
        public string MSG_RCV_TIME { get; set; }
        public string REMARK { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
    }
}
