//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_WS_RESPONSE
    {
        public int WS_CMD_SEQ { get; set; }
        public string ORDER_NO { get; set; }
        public string PNR { get; set; }
        public string PAX_NO { get; set; }
        public string PAX_NAME { get; set; }
        public string FFP_CARD_NO { get; set; }
        public string SEGMENT_NO { get; set; }
        public string FLT_NO { get; set; }
        public string DEPT_STN { get; set; }
        public string DEPT_STN_DESC { get; set; }
        public string DEPT_DATE { get; set; }
        public string DEPT_TIME { get; set; }
        public string ARIV_STN { get; set; }
        public string ARIV_STN_DESC { get; set; }
        public string ARIV_DATE { get; set; }
        public string ARIV_TIME { get; set; }
        public string BCC { get; set; }
        public string IEDF_STATUS { get; set; }
        public string IEDF_DESC { get; set; }
        public string ACTIONRESULT { get; set; }
        public string ERR_CD { get; set; }
        public string ERR_MSG { get; set; }
        public string WS_TYPE { get; set; }
        public string WS_RESPONSE_TEXT { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string OT_NO { get; set; }
    }
}
