//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSD_ORDER_MASTER
    {
        public string ORDER_NO { get; set; }
        public string ORDER_DATE { get; set; }
        public string ARIV_STN { get; set; }
        public string DEPT_FLT_NO { get; set; }
        public string AIRCRAFT_NO { get; set; }
        public string DEPT_GATE { get; set; }
        public string DEPT_TIME { get; set; }
        public string ORDER_NOTICE_TIME { get; set; }
        public string EGAS_CONFIRM_TIME { get; set; }
        public string EGAS_DELIVERY_TIME { get; set; }
        public string CP_ID { get; set; }
        public string ASSIGN_ID { get; set; }
        public string REMARK { get; set; }
        public string ATTACH_MARK { get; set; }
        public string POLAR_REGION_EQUIP_MARK { get; set; }
        public string POLAR_REGION_EQUIP { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string CP_RECEIVE_TIME { get; set; }
        public string CDPI_MARK { get; set; }
        public string IMPORTANT_MARK { get; set; }
        public string SUBMIT_ID { get; set; }
        public string SUBMIT_TIME { get; set; }
        public string CP_SIGNIMAGE { get; set; }
        public string EGAS_PREPARE_START_TIME { get; set; }
        public string EGAS_PREPARE_END_TIME { get; set; }
        public string EGAS_CONFIRM_ID { get; set; }
        public string EGAS_CONFIRM_DATE { get; set; }
        public string ASSIGN_EMPLOYEE_ID { get; set; }
        public string ASSIGN_DATE { get; set; }
        public string ASSIGN_TIME { get; set; }
        public string SUBMIT_DATE { get; set; }
        public string COMPLETE_ID { get; set; }
        public string COMPLETE_DATE { get; set; }
        public string COMPLETE_TIME { get; set; }
        public string CANCEL_ID { get; set; }
        public string CANCEL_DATE { get; set; }
        public string CANCEL_TIME { get; set; }
        public string CANCEL_REMARK { get; set; }
        public string UNSIGN_REMARK { get; set; }
        public string ORDER_FROM { get; set; }
    }
}
