//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSD_MPATROL_ERROR_MASTER
    {
        public string MPATROL_ERROR_NO { get; set; }
        public string PATROL_DATE { get; set; }
        public string PATROL_TIME { get; set; }
        public string FLT_NO { get; set; }
        public string PAX_QTY { get; set; }
        public string ERROR_TIME { get; set; }
        public string REASON { get; set; }
        public string E_COMMENT { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string AC_TYPE { get; set; }
        public string AC_NO { get; set; }
    }
}
