//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSD_APP_VERSION
    {
        public string APP_VER_ID { get; set; }
        public string APP_OS_VER { get; set; }
        public string EFF_DATE { get; set; }
        public string EXP_DATE { get; set; }
        public string APP_VER_REMARK { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string APP_DOWNLOAD_URL { get; set; }
        public string COMPANY { get; set; }
        public string FORCE_UPDATE { get; set; }
    }
}
