//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSD_ASSY_DETAILS
    {
        public string ASSY_NO { get; set; }
        public string DEPT_FLT_NO { get; set; }
        public string AC_TYPE { get; set; }
        public string EFF_DATE { get; set; }
        public string EXP_DATE { get; set; }
        public string SEQ { get; set; }
        public string POSTION_NUMBER { get; set; }
        public string ASSY_CONTENT { get; set; }
        public string CARD_TYPE { get; set; }
        public string CART_TYPE { get; set; }
        public string CLASS_TYPE { get; set; }
        public string ASSY_REMARK { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
    }
}
