//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSN_OPEN_DATA_ORG
    {
        public string EMPLOYEE_NO { get; set; }
        public string CHINESE_NAME { get; set; }
        public string ENGLISH_NAME { get; set; }
        public string NICKNAME { get; set; }
        public short COUNTER { get; set; }
        public int EFFECTIVE_DATE { get; set; }
        public int INEFFECTIVE_DATE { get; set; }
        public string TRANS_MARK1 { get; set; }
        public string TRANS_MARK2 { get; set; }
        public string TRANS_MARK3 { get; set; }
        public string TRANS_MARK4 { get; set; }
        public string TRANS_MARK5 { get; set; }
        public string TRANS_REASON { get; set; }
        public string COMPANY { get; set; }
        public string PART_TIME_COMPANY { get; set; }
        public string DEPARTMENT_12 { get; set; }
        public string DEPARTMENT_PRINT_SEQ { get; set; }
        public string DEPTCODE1 { get; set; }
        public string DEPTCODE2 { get; set; }
        public string DEPTCODE3 { get; set; }
        public string DEPTCODE4 { get; set; }
        public string DEPARTMENT { get; set; }
        public string DEPARTMENT_4 { get; set; }
        public string DEPT_DESC { get; set; }
        public string POSITION_CODE { get; set; }
        public string POSITION_DESC { get; set; }
        public string TRANS_STATUS { get; set; }
        public string TRANS_DESCRIPTION { get; set; }
        public string MANAGER { get; set; }
        public Nullable<short> POS_SEQ { get; set; }
        public string EXT_NO { get; set; }
        public string BUILDING { get; set; }
        public string FLOOR { get; set; }
        public string BUILD_CODE { get; set; }
        public string GROUP_CODE { get; set; }
        public string EMAIL { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
    }
}
