//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUR_PURCHASE_NOTIFY
    {
        public string TRANS_NO { get; set; }
        public string PURCHASE_NO { get; set; }
        public short PURCHASE_SEQ { get; set; }
        public string CODE { get; set; }
        public string STORE_NO { get; set; }
        public string VENDOR_NO { get; set; }
        public string DELIVERY_DATE { get; set; }
        public Nullable<int> WANTED_QTY { get; set; }
        public string DELIVERY_DATE_ADJ { get; set; }
        public string DECIDE_DATE { get; set; }
        public string NTFY_TYPE { get; set; }
        public string NTFY_REMARK { get; set; }
        public string NTFY_CODE { get; set; }
        public string TRANS_STATUS { get; set; }
        public string REF1 { get; set; }
        public string REF2 { get; set; }
        public string REF3 { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
    }
}
