//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUR_FIN_AP_DETAILS_ITEM
    {
        public string REQ_DATE { get; set; }
        public string REQ_DEPT { get; set; }
        public string REQ_SEQ { get; set; }
        public short SUB_SEQ { get; set; }
        public string ITEM_FLAG { get; set; }
        public string ITEM_CODE { get; set; }
        public string DBOCR { get; set; }
        public decimal ITEM_AMT { get; set; }
        public string REF1 { get; set; }
        public string REF2 { get; set; }
        public string REF3 { get; set; }
        public string REF4 { get; set; }
        public string REF5 { get; set; }
        public string REF6 { get; set; }
        public string FM_DATE { get; set; }
        public string TO_DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string REQ_DEPT_SUB { get; set; }
    }
}
