//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUR_ACT_FIN_AP
    {
        public string PERIOD { get; set; }
        public string VENDOR_NO { get; set; }
        public string CODE { get; set; }
        public string CLASS { get; set; }
        public decimal TRANS_QTY { get; set; }
        public string CURRENCY_TYPE { get; set; }
        public decimal CSGMT_COST { get; set; }
        public int TWD_AMT { get; set; }
        public string TRANS_MARK { get; set; }
        public string REQ_DATE { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string AP_SEQ { get; set; }
    }
}
