//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUR_FIN_AP_MASTER
    {
        public string REQ_DATE { get; set; }
        public string REQ_DEPT { get; set; }
        public string REQ_SEQ { get; set; }
        public string PAYEE { get; set; }
        public string CURRENCY_TYPE { get; set; }
        public decimal INVOICE_AMOUNT { get; set; }
        public decimal INVOICE_AMOUNT_NOTAX { get; set; }
        public decimal INVOICE_TAX { get; set; }
        public string PAY_TYPE { get; set; }
        public string PAY_DATE { get; set; }
        public decimal EXRATE { get; set; }
        public string EMERGENCY_MARK { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string TRANS_STATUS { get; set; }
        public string TRANS_ID { get; set; }
        public string TRANS_DATE { get; set; }
        public string TRANS_TIME { get; set; }
        public Nullable<short> REPAY { get; set; }
        public string INVOICE_AMOUNT_SIGN { get; set; }
        public string INVOICE_AMOUNT_NOTAX_SIGN { get; set; }
        public string INVOICE_TAX_SIGN { get; set; }
        public string REQ_AMT_FLAG { get; set; }
        public string REQ_DEPT_SUB { get; set; }
        public string REQ_TYPE { get; set; }
        public string C_TYPE { get; set; }
    }
}
