//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUR_PURCHASE_DETAILS
    {
        public string PURCHASE_NO { get; set; }
        public short PURCHASE_SEQ { get; set; }
        public string CODE { get; set; }
        public Nullable<int> ORDER_QTY { get; set; }
        public Nullable<int> WANTED_QTY { get; set; }
        public Nullable<decimal> ORDER_UNIT_PRICE { get; set; }
        public string STORE_UNIT { get; set; }
        public string ORDER_UNIT { get; set; }
        public string DELIVERY_DATE { get; set; }
        public Nullable<short> COEFFICIENT { get; set; }
        public Nullable<int> TOT_RCV_QTY { get; set; }
        public string LAST_RCV_DATE { get; set; }
        public string PURCHASE_STATUS { get; set; }
        public string PLAN_ETD { get; set; }
        public string TX_NO { get; set; }
        public string REQUEST_NO { get; set; }
        public Nullable<decimal> RETURN_QTY { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string TRANS_NO { get; set; }
        public string TRANS_MARK { get; set; }
        public string LT_MARK { get; set; }
        public string ACT_ETD { get; set; }
        public string ACT_DELIVERY_DATE { get; set; }
    }
}
