//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUR_AUTO_FAX_LOG
    {
        public string FAX_SEQ { get; set; }
        public string FAX_NUMBER { get; set; }
        public string FAX_RECEIVER { get; set; }
        public string FAX_SUBJECT { get; set; }
        public string FAX_SENDER { get; set; }
        public string FAX_FILENAME1 { get; set; }
        public string FAX_FILENAME2 { get; set; }
        public string FAX_STATUS { get; set; }
        public string FAX_ID { get; set; }
        public string FAX_DATE { get; set; }
        public string FAX_TIME { get; set; }
    }
}
