//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUR_FIN_AP_DETAILS_INVOICE
    {
        public string REQ_DATE { get; set; }
        public string REQ_DEPT { get; set; }
        public string REQ_SEQ { get; set; }
        public string CERT_NO { get; set; }
        public string CERT_DATE { get; set; }
        public string CERT_CUSTOMER { get; set; }
        public string CERT_TYPE { get; set; }
        public decimal CERT_AMT { get; set; }
        public string AMOUNT_SIGN { get; set; }
        public decimal CERT_TAX { get; set; }
        public string TAX_SIGN { get; set; }
        public string LEVY { get; set; }
        public string OFFSET { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string REQ_DEPT_SUB { get; set; }
    }
}
