//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUR_PURCHASE_MASTER
    {
        public string PURCHASE_NO { get; set; }
        public string PURCHASE_DATE { get; set; }
        public string PURCHASE_TYPE { get; set; }
        public string RECEIVE_STORE { get; set; }
        public string VENDOR_NO { get; set; }
        public string CURRENCY_TYPE { get; set; }
        public string PAY_TERM { get; set; }
        public string PURCHASE_STATUS { get; set; }
        public string USER_ID { get; set; }
        public string DELIVERY_TYPE { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string DELIVERY_NO { get; set; }
        public string REMARK { get; set; }
        public string DELIVERY_TERM { get; set; }
        public string ADDRESS { get; set; }
        public string FORWARDER_NO { get; set; }
        public Nullable<short> FAX_COUNT { get; set; }
        public string FAX_TIME { get; set; }
        public string FAX_SEQ { get; set; }
        public string FAX_FLAG { get; set; }
        public string COVER_SEQ { get; set; }
        public string DECIDE_ID { get; set; }
        public string DECIDE_DATE { get; set; }
        public string DECIDE_TIME { get; set; }
        public string RETURN_CONFIRM_FLAG { get; set; }
        public string PURCHASE_REMARK { get; set; }
        public string POST_B2B { get; set; }
        public string EMAIL_TIME { get; set; }
        public string PAY_IND { get; set; }
    }
}
