//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class R230_TMP
    {
        public string FLT_NO { get; set; }
        public string SECTOR { get; set; }
        public Nullable<decimal> W_TP { get; set; }
        public Nullable<decimal> P_TP { get; set; }
        public Nullable<decimal> G_TP { get; set; }
        public Nullable<decimal> Y_TP { get; set; }
        public Nullable<decimal> W_P { get; set; }
        public Nullable<decimal> P_P { get; set; }
        public Nullable<decimal> G_P { get; set; }
        public Nullable<decimal> Y_P { get; set; }
        public Nullable<decimal> W_C { get; set; }
        public Nullable<decimal> P_C { get; set; }
        public Nullable<decimal> G_C { get; set; }
        public Nullable<decimal> Y_C { get; set; }
        public Nullable<decimal> W_A { get; set; }
        public Nullable<decimal> P_A { get; set; }
        public Nullable<decimal> G_A { get; set; }
        public Nullable<decimal> Y_A { get; set; }
        public Nullable<decimal> CON { get; set; }
        public Nullable<decimal> W_CON { get; set; }
        public Nullable<decimal> P_CON { get; set; }
        public Nullable<decimal> G_CON { get; set; }
        public Nullable<decimal> Y_CON { get; set; }
        public string SEQ { get; set; }
    }
}
