//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOREDATA
    {
        public decimal STORENO { get; set; }
        public Nullable<decimal> STORETYPE { get; set; }
        public Nullable<decimal> MACHINENO { get; set; }
        public Nullable<decimal> CARRY { get; set; }
        public Nullable<decimal> POS { get; set; }
        public Nullable<decimal> DEPTH { get; set; }
        public Nullable<decimal> WIDTH { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<decimal> ENABLED { get; set; }
    }
}
