//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANS_TO_EDW
    {
        public string TABLE_NAME { get; set; }
        public string TABLE_COLUMNS { get; set; }
        public string TABLE_CONDITION { get; set; }
        public string TRANS_FREQUENCY { get; set; }
        public string MONTHLY_TRANS_DATE { get; set; }
        public string TRANS_OR_NOT { get; set; }
        public string LENGTH_COLUMNS { get; set; }
    }
}
