//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_LOG_TABLE
    {
        public string TRNTB { get; set; }
        public int TRNSEQ { get; set; }
        public string TRNLOG { get; set; }
        public Nullable<System.DateTime> TRNTIME { get; set; }
    }
}
