//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNI_CREW_APPLY_MASTER
    {
        public string APPLY_NO { get; set; }
        public string APPLY_DATE { get; set; }
        public string STORE_NO { get; set; }
        public string APPLICANT { get; set; }
        public string APPLY_USER { get; set; }
        public string APPLY_POSITION { get; set; }
        public string APPLY_DEPARTMENT { get; set; }
        public string ISSUE_TYPE { get; set; }
        public string APPLY_TYPE { get; set; }
        public string REMARK { get; set; }
        public string IS_ALL_APPLY { get; set; }
        public string ALL_APPLY_TYPE { get; set; }
        public string ALL_APPLY_NO { get; set; }
        public string RETURN_DATE { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string IS_CLOSE { get; set; }
        public string APPLY_DEPARTMENT_SUB { get; set; }
        public string SR_NO_FM { get; set; }
        public string SR_NO_TO { get; set; }
        public string SR_REMARK { get; set; }
    }
}
