//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class VFS_FLIGHT_SCHEDULE_TEST
    {
        public string FLIGHT_KEY { get; set; }
        public string CARRIER_CODE { get; set; }
        public string FLIGHT_NO { get; set; }
        public string CODE_SHARE_FLIGHTNO { get; set; }
        public string STATUS_CODE { get; set; }
        public short SECTOR_SEQ { get; set; }
        public string STN_DEPARTURE { get; set; }
        public string STN_ARRIVAL { get; set; }
        public string AIRCRAFT_TYPE { get; set; }
        public Nullable<short> AIRCRAFT_TYPE_SEQ { get; set; }
        public string AIRCRAFT_NO { get; set; }
        public string SERVICE_TYPE { get; set; }
        public string FLIGHT_REGION { get; set; }
        public Nullable<int> ALOADING { get; set; }
        public System.DateTime ACTDATE { get; set; }
        public Nullable<System.DateTime> ACTDATE_LOCAL { get; set; }
        public System.DateTime STD { get; set; }
        public Nullable<System.DateTime> STD_LOCAL { get; set; }
        public System.DateTime STA { get; set; }
        public Nullable<System.DateTime> STA_LOCAL { get; set; }
        public Nullable<System.DateTime> ETD { get; set; }
        public Nullable<System.DateTime> ETD_LOCAL { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public Nullable<System.DateTime> ETA_LOCAL { get; set; }
        public Nullable<System.DateTime> ATD { get; set; }
        public Nullable<System.DateTime> ATD_LOCAL { get; set; }
        public Nullable<System.DateTime> ATA { get; set; }
        public Nullable<System.DateTime> ATA_LOCAL { get; set; }
        public Nullable<System.DateTime> TAKEOFF { get; set; }
        public Nullable<System.DateTime> LANDING { get; set; }
        public Nullable<short> PAX_AVAILABLE_F { get; set; }
        public Nullable<short> PAX_AVAILABLE_C { get; set; }
        public Nullable<short> PAX_AVAILABLE_ED { get; set; }
        public Nullable<short> PAX_AVAILABLE_Y { get; set; }
        public Nullable<short> PAX_BOOKING_F { get; set; }
        public Nullable<short> PAX_BOOKING_C { get; set; }
        public Nullable<short> PAX_BOOKING_ED { get; set; }
        public Nullable<short> PAX_BOOKING_Y { get; set; }
        public Nullable<short> PAX_ACTUAL_F { get; set; }
        public Nullable<short> PAX_ACTUAL_C { get; set; }
        public Nullable<short> PAX_ACTUAL_ED { get; set; }
        public Nullable<short> PAX_ACTUAL_Y { get; set; }
        public string DEP_DELAY_CODE1 { get; set; }
        public string DEP_DELAY_CODE2 { get; set; }
        public string DEP_DELAY_CODE3 { get; set; }
        public string DEP_DELAY_CODE4 { get; set; }
        public string ARR_DELAY_CODE1 { get; set; }
        public string ARR_DELAY_CODE2 { get; set; }
        public string ARR_DELAY_CODE3 { get; set; }
        public string ARR_DELAY_CODE4 { get; set; }
        public string FLIGHT_NO_PATTERN { get; set; }
        public string FLIGHT_ROUTE_NO { get; set; }
        public Nullable<System.DateTime> ROUTE_START_DATETIME { get; set; }
        public string FLIGHTNO_CARGO { get; set; }
        public string FLIGHTNO_RESERVATION { get; set; }
        public string FLIGHTNO_DCS { get; set; }
        public string FLIGHTNO_RA { get; set; }
        public string ORIGINAL_CARRIER_CODE { get; set; }
        public string ORIGINAL_FLIGHT_NO { get; set; }
        public string ORIGINAL_STATUS_CODE { get; set; }
        public Nullable<System.DateTime> ORIGINAL_ACTDATE { get; set; }
        public Nullable<System.DateTime> ORIGINAL_ACTDATE_LOCAL { get; set; }
        public Nullable<System.DateTime> ORIGINAL_STD { get; set; }
        public Nullable<System.DateTime> ORIGINAL_STD_LOCAL { get; set; }
        public Nullable<System.DateTime> ORIGINAL_STA { get; set; }
        public Nullable<System.DateTime> ORIGINAL_STA_LOCAL { get; set; }
        public string BCD_STATUS_CODE { get; set; }
        public Nullable<decimal> FUEL_EXTRA { get; set; }
        public string FUEL_EXTRA_KIND { get; set; }
        public Nullable<decimal> FUEL_PILOT_REQUEST { get; set; }
        public Nullable<decimal> FUEL_TRIP_PLAN { get; set; }
        public Nullable<decimal> FUEL_TAKEOFF_PLAN { get; set; }
        public Nullable<short> FUEL_TAXI_PLAN { get; set; }
        public Nullable<decimal> WT_0_FUEL_PLAN { get; set; }
        public Nullable<decimal> WT_TAKEOFF_PLAN { get; set; }
        public Nullable<short> EST_ENROUTE_TIME { get; set; }
        public Nullable<int> MAX_PAYLOAD_PLAN { get; set; }
        public Nullable<System.DateTime> MAX_PAYLOAD_PLAN_LASTUPDATE { get; set; }
    }
}
