//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class VND_B2B_VENDOR_0121
    {
        public string VENDOR_NO { get; set; }
        public string VENDOR_TYPE { get; set; }
        public string PROFILE_PRODUCT { get; set; }
        public string VENDOR_NAME_CHINESE { get; set; }
        public string VENDOR_NAME_ENGLISH { get; set; }
        public string COUNTRY { get; set; }
        public string CURRENCY_TYPE { get; set; }
        public string AREA_CODE { get; set; }
        public string ADDRESS { get; set; }
        public string INVOICE_COUNTRY { get; set; }
        public string INVOICE_CITY { get; set; }
        public string INVOICE_STATE { get; set; }
        public string INVOICE_ADDRESS { get; set; }
        public string AGENT_ID { get; set; }
        public string AGENT { get; set; }
        public string AGENT_ADDRESS { get; set; }
        public string CLERK { get; set; }
        public string CLERK_ADDRESS { get; set; }
        public string MAIL_ADDRESS { get; set; }
        public string PURCHASE_NOTE_NO { get; set; }
        public string NOTIFY_TYPE_NO { get; set; }
        public string DELIVERY_TERM { get; set; }
        public string PAYMENT_TERM_NO { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string FAX1 { get; set; }
        public string FAX2 { get; set; }
        public string E_MAIL1 { get; set; }
        public string E_MAIL2 { get; set; }
        public string REMARK { get; set; }
        public string FORWARDER_NO { get; set; }
        public string DELIVERY_NO { get; set; }
        public string BANK_NAME { get; set; }
        public string BANK_ADDRESS { get; set; }
        public string ABA_NO { get; set; }
        public string SORT_CODE { get; set; }
        public string CHIPS { get; set; }
        public string IACH { get; set; }
        public string FEDWIRE_NO { get; set; }
        public string LOCAL_CLEARING_BANK_CODE { get; set; }
        public string ACH { get; set; }
        public string OTHERS { get; set; }
        public string SWIFT_CODE { get; set; }
        public string CURRENCY_1 { get; set; }
        public string AC_NO_1 { get; set; }
        public string CURRENCY_2 { get; set; }
        public string AC_NO_2 { get; set; }
        public string CURRENCY_3 { get; set; }
        public string AC_NO_3 { get; set; }
        public string BENEFICIARY_NAME { get; set; }
        public string INTERMEDIARY_BANK_NAME { get; set; }
        public string INTERMEDIARY_BANK_ADDRESS { get; set; }
        public string INTERMEDIARY_BANK_SWIFT_CODE { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string CONSIGNED_FLAG { get; set; }
        public string FLAG_STATUS { get; set; }
        public string VENDOR_KIND { get; set; }
        public string E_MAIL3 { get; set; }
        public string WEBSITE { get; set; }
        public string AUTHENTICATION { get; set; }
        public string COOPERATION { get; set; }
        public string TURN_DATETIME { get; set; }
        public string NEW_VENDOR_NO { get; set; }
    }
}
