//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class VND_SUPPLY
    {
        public string VENDOR_NO { get; set; }
        public string CODE { get; set; }
        public Nullable<int> MINNUM_QTY { get; set; }
        public Nullable<decimal> SUPPLY_PRICE { get; set; }
        public Nullable<short> SUPPLY_COEFFICIENT { get; set; }
        public string SUPPLY_UNIT { get; set; }
        public string PRICE_CHANGE_DATE { get; set; }
        public string CURRENCY_TYPE { get; set; }
        public string RELAY_CODE { get; set; }
        public string EFF_DATE { get; set; }
        public string EXP_DATE { get; set; }
        public string AGENT { get; set; }
        public string AGENT_ADDRESS { get; set; }
        public string CLERK { get; set; }
        public string CLERK_ADDRESS { get; set; }
        public string MAIL_ADDRESS { get; set; }
        public string PAYMENT_TERM_NO { get; set; }
        public string PURCHASE_NOTE_NO { get; set; }
        public string NOTIFY_TYPE_NO { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string FAX1 { get; set; }
        public string FAX2 { get; set; }
        public string E_MAIL1 { get; set; }
        public string E_MAIL2 { get; set; }
        public string REMARK { get; set; }
        public string FORWARDER_NO { get; set; }
        public string DELIVERY_NO { get; set; }
        public string DELIVERY_TERM { get; set; }
        public string STATUS { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string AGENT_ID { get; set; }
        public string SUPPLY_NO { get; set; }
        public string VENDOR_TYPE { get; set; }
        public string APPROVE_DATETIME { get; set; }
        public string APPROVE_USER { get; set; }
        public Nullable<decimal> UPD_PRICE { get; set; }
        public Nullable<short> UPD_COEFFICIENT { get; set; }
        public string UPD_UNIT { get; set; }
        public string UPD_CURRENCY_TYPE { get; set; }
        public Nullable<decimal> ADVISED_PRICE { get; set; }
        public string ADVISED_CURRENCY_TYPE { get; set; }
        public Nullable<decimal> DUTY_FREE_PRICE { get; set; }
        public string DUTY_FREE_CURRENCY_TYPE { get; set; }
        public Nullable<decimal> AVERAGE_PRICE { get; set; }
        public string AVERAGE_CURRENCY_TYPE { get; set; }
        public Nullable<decimal> UPD_AD_PRICE { get; set; }
        public Nullable<decimal> UPD_AV_PRICE { get; set; }
        public Nullable<decimal> UPD_DF_PRICE { get; set; }
        public string UPD_AD_CURRENCY_TYPE { get; set; }
        public string UPD_AV_CURRENCY_TYPE { get; set; }
        public string UPD_DF_CURRENCY_TYPE { get; set; }
        public string STOP_IND { get; set; }
        public string E_MAIL3 { get; set; }
    }
}
