//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class VND_SUBMITTED_DOC_DETAIL
    {
        public string SUBMITTED_NO { get; set; }
        public string VENDOR_NO { get; set; }
        public string CODE { get; set; }
        public string COMPARE_CODE { get; set; }
        public Nullable<int> CONSUMPTION_QTY { get; set; }
        public string CONSUMPTION_UNIT { get; set; }
        public string SELECTED { get; set; }
        public Nullable<decimal> SUPPLY_PRICE { get; set; }
        public Nullable<int> MINNUM_QTY { get; set; }
        public string SEQ { get; set; }
        public Nullable<decimal> EXCHANGE_RATE { get; set; }
        public string CRT_ID { get; set; }
        public string CRT_DATE { get; set; }
        public string CRT_TIME { get; set; }
        public string UPD_ID { get; set; }
        public string UPD_DATE { get; set; }
        public string UPD_TIME { get; set; }
        public string VENDOR_NAME { get; set; }
        public string VENDOR_TYPE { get; set; }
        public string CODE_SHORTNAME { get; set; }
        public string SUPPLY_UNIT { get; set; }
        public string CURRENCY_TYPE { get; set; }
        public string TYPE { get; set; }
        public string VENDOR_STATUS { get; set; }
        public string ADVISED_CURRENCY_TYPE { get; set; }
        public string DUTY_FREE_CURRENCY_TYPE { get; set; }
        public string AVERAGE_CURRENCY_TYPE { get; set; }
        public Nullable<decimal> ADVISED_EX_RATE { get; set; }
        public Nullable<decimal> DUTY_FREE_EX_RATE { get; set; }
        public Nullable<decimal> AVERAGE_EX_RATE { get; set; }
        public Nullable<decimal> ADVISED_PRICE { get; set; }
        public Nullable<decimal> DUTY_FREE_PRICE { get; set; }
        public Nullable<decimal> AVERAGE_PRICE { get; set; }
        public string DELIVERY_TERM { get; set; }
        public string OPEN_TYPE { get; set; }
    }
}
