//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTestSchema
{
    using System;
    using System.Collections.Generic;
    
    public partial class WPAD_DBAS_SMAS
    {
        public string EMPLOYEE_NO { get; set; }
        public string SUBSTITUTED { get; set; }
        public string DEPARTMENT { get; set; }
        public string DEPARTMENT_NO { get; set; }
        public int EFFECTIVE_DATE { get; set; }
        public int INEFFECTIVE_DATE { get; set; }
        public string EXECUTIVE_MARK { get; set; }
    }
}
