// ------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本: 11.0.0.0
//  
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SmasToolkit
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\DetailPageGenerator_AspxCsTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class DetailPageGenerator_AspxCsTemplate : DetailPageGenerator_AspxCsTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Text;
using System.Collections;
using DDSC.OracleADO;
using System.Data;

namespace SMAS.MainWebAP.");
            
            #line 18 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\DetailPageGenerator_AspxCsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.GetPageCategory(config.PageId)));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public partial class ");
            
            #line 20 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\DetailPageGenerator_AspxCsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(config.PageId));
            
            #line default
            #line hidden
            this.Write(@" : SMAS.MainWebAP.Common.BasePage
    {
        const bool bSupportHelp = true;

        #region Page_Load

        protected void Page_Load(object sender, EventArgs e)
        {
            try
            {
                if (!Page.IsPostBack)
                {
                    // 初始化控制項(例如: DropDownList, RadioButtonList, ...)

                    // 如果沒有前一頁(或者前一頁不為");
            
            #line 34 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\DetailPageGenerator_AspxCsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(config.ParentPageId));
            
            #line default
            #line hidden
            this.Write(")，就忽略後續動作\r\n                    ");
            
            #line 35 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\DetailPageGenerator_AspxCsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(config.ParentPageId));
            
            #line default
            #line hidden
            this.Write(" previousPage = Page.PreviousPage as ");
            
            #line 35 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\DetailPageGenerator_AspxCsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(config.ParentPageId));
            
            #line default
            #line hidden
            this.Write(";\r\n                    if (previousPage == null)\r\n                    {\r\n\t\t\t     " +
                    "       ");
            
            #line 38 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\DetailPageGenerator_AspxCsTemplate.tt"

				            PushIndent("                        ");

				            foreach (var button in config.Buttons)
				            {
					            WriteLine(button.RenderVisibility(""));
				            }
						
				            ClearIndent();
			            
            
            #line default
            #line hidden
            this.Write(@"                        return;
                    }

                    string buttonType = (previousPage.g_ButtonType ?? string.Empty).Trim().ToUpper();
                    ViewState[""Action""] = buttonType;
                    hidACT_TYPE.Value = buttonType;

                    // 當使用者操作為 [新增]，則不載入任何資料
                    if (buttonType.ToString() != ""ADD"") 
                    {
                        // 根據前一頁選取內容，將相關資料載入到對應控制項
                        LoadData(previousPage);
                    }
                    
                    // 根據前一頁選取動作，設定控制項是否可編輯或者唯讀
                    switch (buttonType)
                    {
                        ");
            
            #line 65 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\DetailPageGenerator_AspxCsTemplate.tt"

                            List<string> buttonTypes = new List<string> { 
                                "ADD", 
                                "UPD", 
                                "DEL", 
                                "COPY", 
                                "QRY"
                            };                           
                            
                            PushIndent("                        ");

                            foreach (var buttonType in buttonTypes)
                            {
                                WriteLine("case \"{0}\":", buttonType);
                                WriteLine("    // 顯示隱藏按鈕");
                                foreach (var button in config.Buttons)
				                {
					                WriteLine("    " + button.RenderVisibility(buttonType));
				                }
                                WriteLine("    // 設定控制項是否可讀寫");
		                        foreach (var column in config.Columns)
		                        {
                                    string str = column.RenderWritablity(buttonType);
                                    if(!string.IsNullOrEmpty(str))
			                            WriteLine("    " + str);
		                        }
                                WriteLine("    // 設定控制項初始值");
		                        foreach (var column in config.Columns)
		                        {
                                    string str = column.RenderInitValue(buttonType);
                                    if(!string.IsNullOrEmpty(str))
			                            WriteLine("    " + str);
		                        }
                                WriteLine("    break;");
                                WriteLine("");
                            }

                            ClearIndent();
                        
            
            #line default
            #line hidden
            this.Write(@"                        default:
                            throw new Exception(string.Format(""Page_Load, 尚未處理當 buttonType = {0}對應的動作"", buttonType));
                    }
                }
            }
            catch (Exception ex)
            {
                showException(string.Format(""{0}, StackTrace: {1}"", ex.Message, ex.StackTrace.ToString()));
            }
        }

        #region GetParams
        /// <summary>
        /// 改善原本參數塞入的方式
        /// </summary>
        private ArrayList GetParams(dbAccess dba, string sql, Dictionary<string, string> dict)
        {
            List<string> sqlParams = sql.Split(new string[] { "" "" }, StringSplitOptions.RemoveEmptyEntries)
                                        .Where(t => t.Trim().StartsWith("":""))
                                        .Select(t => t.Trim().Substring(1).ToUpper())
                                        .ToList();

            ArrayList arrParam = new ArrayList();

            foreach (var key in dict.Keys)
            {
                if (sqlParams.Contains(key))
                {
                    arrParam.Add(dba.GetOracleParam("":"" + key, dict[key]));
                }
            }

            return arrParam;
        }
        #endregion
        #region FetchData
        private DataTable FetchData(");
            
            #line 140 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\DetailPageGenerator_AspxCsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(config.ParentPageId));
            
            #line default
            #line hidden
            this.Write(@" previousPage)
        {
            if (previousPage == null) throw new ArgumentNullException(""previousPage"");
            if (previousPage.g_GridKey == null) throw new ArgumentNullException(""previousPage.g_GridKey"");

            // (1) 定義傳入參數
            Dictionary<string, string> dictParams = new Dictionary<string, string>(previousPage.g_GridKey);
            ");
            
            #line 147 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\DetailPageGenerator_AspxCsTemplate.tt"

                PushIndent("            ");

				foreach (var field in SqlUtils.GetFields(config.MasterConfig.SearchSql))
				{
                    WriteLine("string {0} = dictParams[\"{0}\"];", field);
				}
                
                ClearIndent();
            
            
            #line default
            #line hidden
            this.Write("\r\n            // (2) 組合SQL\r\n            StringBuilder sb = new StringBuilder();\r\n" +
                    "            ");
            
            #line 160 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\DetailPageGenerator_AspxCsTemplate.tt"

                PushIndent("            ");

                string sql = SqlUtils.GenerateFetchDataSql(config);
	
				foreach (var aSqlLine in SqlUtils.GetFormattedSqlLines(sql))
				{
					WriteLine("sb.Append(\" {0}\");", aSqlLine);
				}             
   
                ClearIndent();
            
            
            #line default
            #line hidden
            this.Write(@"            
            // (3) 根據組合SQL判斷實際要加入的參數
            dbAccess dba = new dbAccess();
            ArrayList arrParam = GetParams(dba, sb.ToString(), dictParams);

            // (4) 查詢資料
            DataSet ds = dba.runExecuteQuery(""FetchData"", sb.ToString(), arrParam);
            if (ErrorCtrl(ds))
            {
                return ds.Tables[""FetchData""];
            }
            else
            {
                ClientScript.RegisterClientScriptBlock(this.GetType(), ""Result"", ""<script language='javascript'> $(document).ready(function () { alert('此筆資料已被刪除，請重新選擇！'); $('#btnExit')[0].click(); }); </script>"");
                return null;
            }
        }
        #endregion
        #region LoadData
        /// <summary>
        /// 根據前一頁面所選條件，將相關資料載入到對應控制項
        /// </summary>
        /// <param name=""p_FORWARDER_NO""></param>
        /// <returns></returns>
        private void LoadData(");
            
            #line 196 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\DetailPageGenerator_AspxCsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(config.ParentPageId));
            
            #line default
            #line hidden
            this.Write(" previousPage)\r\n        {\r\n            DataTable dt = FetchData(previousPage);\r\n\r" +
                    "\n            if (dt == null) return;\r\n            SetCtrlValue(this.Details, dt)" +
                    ";\r\n\r\n            // TODO: 如果有SetCtrlValue無法設定的控制項，請在此手動設定\r\n        }\r\n        #e" +
                    "ndregion\r\n\r\n        #endregion\r\n\r\n        #region btnSave_Click\r\n\r\n        /// <" +
                    "summary>\r\n        /// 儲存\r\n        /// </summary>\r\n        /// <param name=\"sende" +
                    "r\"></param>\r\n        /// <param name=\"e\"></param>\r\n        protected void btnSav" +
                    "e_Click(object sender, EventArgs e)\r\n        {\r\n            string buttonType = " +
                    "Convert.ToString(ViewState[\"Action\"] ?? \"NULL\").Trim().ToUpper();\r\n\r\n           " +
                    " try\r\n            {\r\n                DataSet result = null;\r\n\r\n                s" +
                    "witch (buttonType)\r\n                {\r\n                    case \"ADD\":\r\n        " +
                    "                result = DoAdd();\r\n                        break;\r\n\r\n           " +
                    "         case \"UPD\":\r\n                        result = DoUpdate();\r\n            " +
                    "            break;\r\n\r\n                    case \"DEL\":\r\n                        r" +
                    "esult = DoDelete();\r\n                        break;\r\n\r\n                    case " +
                    "\"COPY\":\r\n                        result = DoCopy();\r\n                        bre" +
                    "ak;\r\n\r\n                    default:\r\n                        throw new Exception" +
                    "(string.Format(\"btnSave_Click, 尚未處理當 buttonType = {0} 對應的動作\", buttonType));\r\n   " +
                    "             }\r\n\r\n                // 寫入script至client端\r\n                regScript" +
                    "(result, buttonType);\r\n            }\r\n            catch (Exception ex)\r\n        " +
                    "    {\r\n                showException(string.Format(\"{0}, StackTrace: {1}\", ex.Me" +
                    "ssage, ex.StackTrace.ToString()));\r\n            }\r\n        }\r\n\r\n        #region " +
                    "DoAdd\r\n        private DataSet DoAdd()\r\n        {\r\n            string action = \"" +
                    "ADD\";\r\n\r\n            ddscDataSet ddscDs = new ddscDataSet();\r\n\r\n            ddsc" +
                    "DataTable ddscDt = ddscDs.createDataTable(\"");
            
            #line 262 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\DetailPageGenerator_AspxCsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(config.TableName));
            
            #line default
            #line hidden
            this.Write("\");\r\n\r\n            ddscDt.addNewRow();\r\n            ddscDt.setColumnValue(\"action" +
                    "\", \"string\", action);\r\n\r\n            // 設定使用者輸入內容\r\n            ");
            
            #line 268 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\DetailPageGenerator_AspxCsTemplate.tt"

                PushIndent("            ");

                foreach (var column in config.Columns)
                {
                    if(column.Name == "UPD_ID" ||
                       column.Name == "UPD_DATE" ||
                       column.Name == "UPD_TIME" ||
                       column.Name == "CRT_ID" ||
                       column.Name == "CRT_DATE" ||
                       column.Name == "CRT_TIME")continue;

                    WriteLine("ddscDt.setColumnValue(\"{0}\", \"string\", {1}.Text.Trim());", column.Name, column.GetInputId());
                }

                ClearIndent();
            
            
            #line default
            #line hidden
            this.Write(@"            // 設定[更新者]、[更新日期]、[更新時間]
            ddscDt.setColumnValue(""UPD_ID"", ""string"", User.Identity.Name);
            ddscDt.setColumnValue(""UPD_DATE"", ""string"", SystemDate);
            ddscDt.setColumnValue(""UPD_TIME"", ""string"", SystemTime);
            // 設定[建檔者]、[建檔日期]、[建檔時間]
            ddscDt.setColumnValue(""CRT_ID"", ""string"", User.Identity.Name);
            ddscDt.setColumnValue(""CRT_DATE"", ""string"", SystemDate);
            ddscDt.setColumnValue(""CRT_TIME"", ""string"", SystemTime);
            
            ddscDs.addddscDataTable(ddscDt);

            DataBase dataBase = new DataBase();
            return dataBase.AdditionParameter(ddscDs);
        }
        #endregion

        #region DoUpdate
        private DataSet DoUpdate()
        {
            string action = ""UPD"";

            ddscDataSet ddscDs = new ddscDataSet();

            ddscDataTable ddscDt = ddscDs.createDataTable(""");
            
            #line 308 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\DetailPageGenerator_AspxCsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(config.TableName));
            
            #line default
            #line hidden
            this.Write("\");\r\n\r\n            ddscDt.addNewRow();\r\n            ddscDt.setColumnValue(\"action" +
                    "\", \"string\", action);\r\n\r\n            // 設定使用者輸入內容\r\n            ");
            
            #line 314 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\DetailPageGenerator_AspxCsTemplate.tt"

                PushIndent("            ");

                foreach (var column in config.Columns)
                {
                    if(column.Name == "UPD_ID" ||
                       column.Name == "UPD_DATE" ||
                       column.Name == "UPD_TIME" ||
                       column.Name == "CRT_ID" ||
                       column.Name == "CRT_DATE" ||
                       column.Name == "CRT_TIME")continue;

                    WriteLine("ddscDt.setColumnValue(\"{0}\", \"string\", {1}.Text.Trim());", column.Name, column.GetInputId());
                }

                ClearIndent();
            
            
            #line default
            #line hidden
            this.Write(@"            // 設定[更新者]、[更新日期]、[更新時間]
            ddscDt.setColumnValue(""UPD_ID"", ""string"", User.Identity.Name);
            ddscDt.setColumnValue(""UPD_DATE"", ""string"", SystemDate);
            ddscDt.setColumnValue(""UPD_TIME"", ""string"", SystemTime);

            // 將主鍵值欄位加入Where條件
            ");
            
            #line 337 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\DetailPageGenerator_AspxCsTemplate.tt"

                PushIndent("            ");

                foreach (var column in config.Columns)
                {
                    if(!column.IsPrimaryKey)continue;

                    WriteLine("ddscDt.setWhereValue(\"{0}\", {1}.Text.Trim());", column.Name, column.GetInputId());
                }

                ClearIndent();
            
            
            #line default
            #line hidden
            this.Write(@"
            ddscDs.addddscDataTable(ddscDt);

            DataBase dataBase = new DataBase();
            return dataBase.AdditionParameter(ddscDs);
        }
        #endregion

        #region DoDelete
        private DataSet DoDelete()
        {
            string action = ""DEL"";

            ddscDataSet ddscDs = new ddscDataSet();

            ddscDataTable ddscDt = ddscDs.createDataTable(""");
            
            #line 364 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\DetailPageGenerator_AspxCsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(config.TableName));
            
            #line default
            #line hidden
            this.Write("\");\r\n\r\n            ddscDt.addNewRow();\r\n            ddscDt.setColumnValue(\"action" +
                    "\", \"string\", action);\r\n\r\n            // 將主鍵值欄位加入Where條件\r\n            ");
            
            #line 370 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\DetailPageGenerator_AspxCsTemplate.tt"

                PushIndent("            ");

                foreach (var column in config.Columns)
                {
                    if(!column.IsPrimaryKey)continue;

                    WriteLine("ddscDt.setWhereValue(\"{0}\", {1}.Text.Trim());", column.Name, column.GetInputId());
                }

                ClearIndent();
            
            
            #line default
            #line hidden
            this.Write(@"
            ddscDs.addddscDataTable(ddscDt);

            DataBase dataBase = new DataBase();
            return dataBase.AdditionParameter(ddscDs);
        }
        #endregion

        #region DoCopy
        private DataSet DoCopy()
        {
            string action = ""COPY"";

            ddscDataSet ddscDs = new ddscDataSet();

            ddscDataTable ddscDt = ddscDs.createDataTable(""");
            
            #line 397 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\DetailPageGenerator_AspxCsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(config.TableName));
            
            #line default
            #line hidden
            this.Write("\");\r\n\r\n            ddscDt.addNewRow();\r\n            ddscDt.setColumnValue(\"action" +
                    "\", \"string\", action);\r\n\r\n            // 設定使用者輸入內容\r\n            ");
            
            #line 403 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\DetailPageGenerator_AspxCsTemplate.tt"

                PushIndent("            ");

                foreach (var column in config.Columns)
                {
                    if(column.Name == "UPD_ID" ||
                       column.Name == "UPD_DATE" ||
                       column.Name == "UPD_TIME" ||
                       column.Name == "CRT_ID" ||
                       column.Name == "CRT_DATE" ||
                       column.Name == "CRT_TIME")continue;

                    WriteLine("ddscDt.setColumnValue(\"{0}\", \"string\", {1}.Text.Trim());", column.Name, column.GetInputId());
                }

                ClearIndent();
            
            
            #line default
            #line hidden
            this.Write(@"            // 設定[更新者]、[更新日期]、[更新時間]
            ddscDt.setColumnValue(""UPD_ID"", ""string"", User.Identity.Name);
            ddscDt.setColumnValue(""UPD_DATE"", ""string"", SystemDate);
            ddscDt.setColumnValue(""UPD_TIME"", ""string"", SystemTime);
            // 設定[建檔者]、[建檔日期]、[建檔時間]
            ddscDt.setColumnValue(""CRT_ID"", ""string"", User.Identity.Name);
            ddscDt.setColumnValue(""CRT_DATE"", ""string"", SystemDate);
            ddscDt.setColumnValue(""CRT_TIME"", ""string"", SystemTime);

            ddscDs.addddscDataTable(ddscDt);

            DataBase dataBase = new DataBase();
            return dataBase.AdditionParameter(ddscDs);
        }
        #endregion

        /// <summary>
        /// 刪除
        /// </summary>
        /// <param name=""sender""></param>
        /// <param name=""e""></param>
        protected void btnDELETE_Click(object sender, EventArgs e)
        {
            btnSave_Click(null, null);
        }

        #endregion
    }
}");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\DetailPageGenerator_AspxCsTemplate.tt"

private global::SmasToolkit.DetailPageGeneratorConfig _configField;

/// <summary>
/// Access the config parameter of the template.
/// </summary>
private global::SmasToolkit.DetailPageGeneratorConfig config
{
    get
    {
        return this._configField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool configValueAcquired = false;
if (this.Session.ContainsKey("config"))
{
    if ((typeof(global::SmasToolkit.DetailPageGeneratorConfig).IsAssignableFrom(this.Session["config"].GetType()) == false))
    {
        this.Error("參數 \'config\' 的型別 \'SmasToolkit.DetailPageGeneratorConfig\' 不符合傳遞至範本之資料的型別。");
    }
    else
    {
        this._configField = ((global::SmasToolkit.DetailPageGeneratorConfig)(this.Session["config"]));
        configValueAcquired = true;
    }
}
if ((configValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("config");
    if ((data != null))
    {
        if ((typeof(global::SmasToolkit.DetailPageGeneratorConfig).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("參數 \'config\' 的型別 \'SmasToolkit.DetailPageGeneratorConfig\' 不符合傳遞至範本之資料的型別。");
        }
        else
        {
            this._configField = ((global::SmasToolkit.DetailPageGeneratorConfig)(data));
        }
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public class DetailPageGenerator_AspxCsTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
