// ------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本: 11.0.0.0
//  
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SmasToolkit
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\MasterPageGenerator_AspxTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class MasterPageGenerator_AspxTemplate : MasterPageGenerator_AspxTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("<%@ Page Language=\"C#\" AutoEventWireup=\"true\" CodeBehind=\"");
            
            #line 7 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\MasterPageGenerator_AspxTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(config.PageId));
            
            #line default
            #line hidden
            this.Write(".aspx.cs\" Inherits=\"SMAS.MainWebAP.");
            
            #line 7 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\MasterPageGenerator_AspxTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.GetPageCategory(config.PageId)));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 7 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\MasterPageGenerator_AspxTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(config.PageId));
            
            #line default
            #line hidden
            this.Write(@""" %>
<%@ Register TagPrefix=""ddsc"" Namespace=""DDSC.CustomServerControl"" Assembly=""DDSC.CustomServerControl"" %>
<html xmlns=""http://www.w3.org/1999/xhtml"">
<head id=""Head"" runat=""server"">
    <meta http-equiv=""Content-Type"" content=""text/html; charset=utf-8"" />
    <meta http-equiv=""X-UA-Compatible"" content=""IE=9"" />
    <title></title>
    <link href=""../styles/style.css"" rel=""stylesheet"" type=""text/css"" />
    <link href=""../Styles/jquery-ui.css"" rel=""stylesheet"" />
    <link href=""../Styles/reset.css"" rel=""stylesheet"" type=""text/css"" />
    <script src=""../Scripts/jquery-1.8.3.js""></script>
    <script src=""../Scripts/FunctionHander.js""></script>
    <script src=""../Scripts/scroll.js""></script>
    <script src=""../Scripts/GridDataBind.js""></script>
    <script src=""../Scripts/BlockUI.js""></script>
    <script src=""../Scripts/jquery-ui.js""></script>
    <script src=""js/");
            
            #line 23 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\MasterPageGenerator_AspxTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(config.PageId));
            
            #line default
            #line hidden
            this.Write(@".js""></script>
    <style type=""text/css"">
        #ProgramPageIndex {width: 28px;}
    </style>
</head>
<body bgcolor=""#e7eef4"">
    <form id=""form1"" runat=""server"">
        <div id=""Wrapper"">
            <div id=""pageTop"">
                <div class=""Navgation""><asp:Label ID=""User_Info"" runat=""server"" Text=""""></asp:Label></div>
                <div class=""TitleName01""><asp:Label ID=""lbl");
            
            #line 33 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\MasterPageGenerator_AspxTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(config.PageId));
            
            #line default
            #line hidden
            this.Write("\" runat=\"server\" Text=\"\"></asp:Label>-");
            
            #line 33 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\MasterPageGenerator_AspxTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(config.PageId));
            
            #line default
            #line hidden
            this.Write("</div>\r\n                <div class=\"linespace\">\r\n                  <div>\r\n\t\t\t\t\t");
            
            #line 36 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\MasterPageGenerator_AspxTemplate.tt"

						PushIndent("					");

						foreach (var button in config.Buttons)
						{
							WriteLine(button.RenderMasterAspx());
						}
						
						ClearIndent();
					
            
            #line default
            #line hidden
            this.Write("                  </div>\r\n                    <div class=\"round\">\r\n              " +
                    "          <table border=\"0\" align=\"center\" cellpadding=\"5\" class=\"table01\" style" +
                    "=\"width: 98%; margin-top: 20px;\">\r\n\t\t\t\t\t\t\t");
            
            #line 49 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\MasterPageGenerator_AspxTemplate.tt"

								PushIndent("							");

								foreach (var hc in config.QueryConditions)
								{
									WriteLine("<tr>");
									WriteLine("	<td>");
									WriteLine("		{0}", hc.RenderLabel());
									WriteLine("	</td>");
									WriteLine("	<td>");
									WriteLine("		{0}", hc.RenderInput());
									WriteLine("	</td>");
									WriteLine("</tr>");
									//WriteLine(queryCondition.RenderAspx());
								}

								ClearIndent();
							
            
            #line default
            #line hidden
            this.Write(@"                        </table>
                    </div>
                    <div class=""round"">
                        <div style=""position: relative; width: 100%; height: 400px;"" onclick='GridEventHandler(event,this.id);' class=""Program"" id=""Program""></div>
                        <%--換頁區塊--%>
                    </div>
					");
            
            #line 73 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\MasterPageGenerator_AspxTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(config.RenderGridTableFooter()));
            
            #line default
            #line hidden
            this.Write(@"
                        <div id=""ProgramPageInfo"" class=""moretxt"" style=""width: 50%; text-align: left""></div>
                        <div id=""Span1"" style=""width: 100%; text-align: right"">
                            <input type=""button"" id=""ProgrambtnFirst"" value=""第一頁"" class=""BtnOn"" />
                            <input type=""button"" id=""ProgrambtnPrev"" value=""上一頁"" class=""BtnOn"" />
                            <span id=""ProgramPages""></span>
                            <input type=""button"" id=""ProgrambtnNext"" value=""下一頁"" class=""BtnOn"" />
                            <input type=""button"" id=""ProgrambtnLast"" value=""最後頁"" class=""BtnOn"" />
                            &#160;<label id=""lblGO_TO1"">Go to</label>&#160;<input type=""text"" id=""ProgramPageIndex"" class=""width_4"" maxlength=""4"" value="""" />
                            <input type=""button"" id=""ProgrambtnGoto"" class=""BtnOn"" value=""GO"" class=""btn_Go"" name=""Go"" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</body>
</html>");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Backup\Markdown\EvaToolkits\SmasToolkit\MasterPageGenerator_AspxTemplate.tt"

private global::SmasToolkit.MasterPageGeneratorConfig _configField;

/// <summary>
/// Access the config parameter of the template.
/// </summary>
private global::SmasToolkit.MasterPageGeneratorConfig config
{
    get
    {
        return this._configField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool configValueAcquired = false;
if (this.Session.ContainsKey("config"))
{
    if ((typeof(global::SmasToolkit.MasterPageGeneratorConfig).IsAssignableFrom(this.Session["config"].GetType()) == false))
    {
        this.Error("參數 \'config\' 的型別 \'SmasToolkit.MasterPageGeneratorConfig\' 不符合傳遞至範本之資料的型別。");
    }
    else
    {
        this._configField = ((global::SmasToolkit.MasterPageGeneratorConfig)(this.Session["config"]));
        configValueAcquired = true;
    }
}
if ((configValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("config");
    if ((data != null))
    {
        if ((typeof(global::SmasToolkit.MasterPageGeneratorConfig).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("參數 \'config\' 的型別 \'SmasToolkit.MasterPageGeneratorConfig\' 不符合傳遞至範本之資料的型別。");
        }
        else
        {
            this._configField = ((global::SmasToolkit.MasterPageGeneratorConfig)(data));
        }
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public class MasterPageGenerator_AspxTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
